## Load all datasets as Data Frames

In [1]:
import pandas as pd
import re
import numpy as np

In [2]:
splits = {'explicit_train': 'AbuseEval/explicit_train.jsonl', 'explicit_test': 'AbuseEval/explicit_test.jsonl', 'implicit_train': 'AbuseEval/implicit_train.jsonl', 'implicit_test': 'AbuseEval/implicit_test.jsonl'}

df_AbuseEval_explicit_train = pd.read_json("hf://datasets/Shuwan/cadet-datasets/" + splits["explicit_train"], lines=True)
df_AbuseEval_explicit_test = pd.read_json("hf://datasets/Shuwan/cadet-datasets/" + splits["explicit_test"], lines=True)
df_AbuseEval_implicit_train = pd.read_json("hf://datasets/Shuwan/cadet-datasets/" + splits["implicit_train"], lines=True)
df_AbuseEval_implicit_test = pd.read_json("hf://datasets/Shuwan/cadet-datasets/" + splits["implicit_test"], lines=True)

In [3]:
splits = {'explicit_train': 'DynaHate/explicit_train.jsonl', 'explicit_test': 'DynaHate/explicit_test.jsonl', 'implicit_train': 'DynaHate/implicit_train.jsonl', 'implicit_test': 'DynaHate/implicit_test.jsonl'}

df_DynaHate_explicit_train = pd.read_json("hf://datasets/Shuwan/cadet-datasets/" + splits["explicit_train"], lines=True)
df_DynaHate_explicit_test = pd.read_json("hf://datasets/Shuwan/cadet-datasets/" + splits["explicit_test"], lines=True)
df_DynaHate_implicit_train = pd.read_json("hf://datasets/Shuwan/cadet-datasets/" + splits["implicit_train"], lines=True)
df_DynaHate_implicit_test = pd.read_json("hf://datasets/Shuwan/cadet-datasets/" + splits["implicit_test"], lines=True)

In [4]:
splits = {'explicit_train': 'Implicit-Hate-Corpus/explicit_train.jsonl', 'explicit_test': 'Implicit-Hate-Corpus/explicit_test.jsonl', 'implicit_train': 'Implicit-Hate-Corpus/implicit_train.jsonl', 'implicit_test': 'Implicit-Hate-Corpus/implicit_test.jsonl'}

df_Implicit_Hate_Corpus_explicit_train = pd.read_json("hf://datasets/Shuwan/cadet-datasets/" + splits["explicit_train"], lines=True)
df_Implicit_Hate_Corpus_explicit_test = pd.read_json("hf://datasets/Shuwan/cadet-datasets/" + splits["explicit_test"], lines=True)
df_Implicit_Hate_Corpus_implicit_train = pd.read_json("hf://datasets/Shuwan/cadet-datasets/" + splits["implicit_train"], lines=True)
df_Implicit_Hate_Corpus_implicit_test = pd.read_json("hf://datasets/Shuwan/cadet-datasets/" + splits["implicit_test"], lines=True)

In [5]:
splits = {'explicit_train': 'IsHate/explicit_train.jsonl', 'explicit_test': 'IsHate/explicit_test.jsonl', 'implicit_train': 'IsHate/implicit_train.jsonl', 'implicit_test': 'IsHate/implicit_test.jsonl'}
df_IsHate_explicit_train = pd.read_json("hf://datasets/Shuwan/cadet-datasets/" + splits["explicit_train"], lines=True)
df_IsHate_explicit_test = pd.read_json("hf://datasets/Shuwan/cadet-datasets/" + splits["explicit_test"], lines=True)
df_IsHate_implicit_train = pd.read_json("hf://datasets/Shuwan/cadet-datasets/" + splits["implicit_train"], lines=True)
df_IsHate_implicit_test = pd.read_json("hf://datasets/Shuwan/cadet-datasets/" + splits["implicit_test"], lines=True)

## Find all Target values

In [6]:
all_dfs = [df_AbuseEval_explicit_train, df_AbuseEval_explicit_test, df_AbuseEval_implicit_train, df_AbuseEval_implicit_test,
           df_DynaHate_explicit_train, df_DynaHate_explicit_test, df_DynaHate_implicit_train, df_DynaHate_implicit_test,
           df_Implicit_Hate_Corpus_explicit_train, df_Implicit_Hate_Corpus_explicit_test, df_Implicit_Hate_Corpus_implicit_train, df_Implicit_Hate_Corpus_implicit_test,
           df_IsHate_explicit_train, df_IsHate_explicit_test, df_IsHate_implicit_train, df_IsHate_implicit_test]  

all_dfs_concat = pd.concat(all_dfs, ignore_index=True)
all_dfs_concat['target'].unique()

array(['Abnormality', 'Gender', 'Race', ..., 'Hunting knives', 'Life',
       'Motorrad'], shape=(1326,), dtype=object)

In [7]:
# Show all unique values without truncation
import numpy as np
np.set_printoptions(threshold=np.inf)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)
print(all_dfs_concat['target'].unique())

['Abnormality' 'Gender' 'Race' 'Immigration Status' 'Abnormal Activity'
 'Religion' 'Relationship' 'Mental Health'
 'Violence and Threat to Government' 'Violence'
 'Sexuality and Sexual Preferences' 'none' 'Anger' 'Politics' 'Aggression'
 'Fascism' 'Sexual Preferences' 'Alcoholism' 'Emotion' 'Sports' 'Abnormal'
 'Abnormal Behavior' 'Abelness/Disability' 'Gun Control' 'Abnormal System'
 'Abnormal_Emotion' 'Social unrest' 'Sex and Sexual Preferences'
 'Sexual and Sexual Preferences' 'Narcissism' 'Security' 'Crime'
 'Mobility' 'Slowness' 'Corruption' 'Gun control' 'Abuse' 'Furniture'
 'Stalking' 'Hungry' 'Sarcasm' 'Electrical' 'Health' 'Terrorism' 'Unknown'
 'Animal' 'Sociopath' 'Hair' 'Abience/Disability' 'Irrelevant' 'Rape'
 'Threat' 'Social Issues' 'Food & Dining' 'Abhorrent' 'Abortion'
 'Abnormal Language' 'Hate Speech' 'Comedy' 'Sexual Misconduct' 'Dementia'
 'Entertainment' 'Class' 'Domestic Abuse' 'Bullying' 'Roads'
 'Substance Abuse' 'Music' 'Abduction' 'Beauty' 'Europe' 'Philosophy'
 'Money' 'Romance' 'Business' 'Business Closure' 'Election' 'Football'
 'Family' 'Child Welfare' 'Gaming' 'Innocence' 'Legal' 'Trust'
 'Ableness/Disability' 'Education' 'Socialism' 'Injury' 'Sex Offenders'
 'Wrestling' 'Weather' 'Nationality' 'Justice' 'iPhone' 'Soccer'
 'Political' 'Climate Change' 'Abience' 'Poverty' 'Finance'
 'Gun Free Zone' 'Apology' 'Love' 'Railways' 'Forgiveness' 'Weight Loss'
 'Social' 'Social Interaction' 'Relaxation' 'Blame' 'Sleep' 'Child Abuse'
 'Sanctions Regime' 'GunControl' 'Birthday' 'Societal issues' 'Age'
 'LGBTQ+' 'Relationships' 'Marriage' 'Payment' 'Inability' 'Frame Rate'
 'Safety' 'Stress' 'Literature' 'Welfare' 'Antifa' 'Psychology'
 'Dairy Queen' 'Career' 'Democracy' 'Technology' 'Friend' 'Banking'
 'Leadership' 'Confidence' 'Food' 'Accident' 'Human Rights' 'Empathy'
 'NRA and telecom industry' 'Medical' 'Community Gardening' 'Government'
 'Appearance' 'GunControlNow' 'Allergy' 'Taxation' 'Gun Safety' 'Culture'
 'Gun Violence' 'Abuse of my power' 'Economy' 'Price' 'Grief'
 'Self defense' 'Generosity' 'LGBTURE' 'Parenting' 'Gun Lobby'
 'Abdominal pain' 'Transport' 'Anxiety' 'Social Justice' 'Mental health'
 'Gun Deaths' 'Speed' 'History' 'School Spirit' 'Income' 'Physics' 'Genre'
 'Attention Seeking' 'War' 'Trustworthiness' 'Child Pornography'
 'Conflict' 'Catching' 'Follow Back' 'Economics' 'Audio' 'Treason'
 'Tourism' 'Krav Maga' 'Medicine' 'Migration Status' 'Euthanasia'
 'Patriot' 'Friendship' 'Geography' 'Trauma' 'Basketball' 'Brexit'
 'Carbon' 'Cooking' 'Collaboration' 'Misinformation' 'Intelligence'
 'Defense' 'Shopping' 'Housing Associations' 'Social Media' 'Mood'
 'Credit' 'Job' 'Alien' 'Skin Care' 'Skinny' 'Happiness' 'Communication'
 'Diabetes' 'Child' 'LGBTQ' 'Demographics' 'Grammar' 'Network TV' 'AntiFA'
 'Gun Control and The Enemy In The Land' 'Housing' 'Crime Rate'
 'Concession Stand' 'Emotions' 'Healthcare' 'Freedom' 'Heart Attack'
 'Abbling/Disability' 'Scam' 'Agriculture' 'Hate Crime' 'Entrepreneur'
 'Inappropriate' 'Job Search' 'Construction' 'Antideutsch' 'Greeting'
 'Trash' 'Abnormal Sentiment' 'Criminal' 'Transgender' 'Law' 'Clothing'
 'Creativity' 'Hate' 'Dog' 'Gang Related Violence' 'Lawsuits' 'Affection'
 'Environment' 'Gun Control and Healthcare' 'Homosexuality'
 ' Sexuality and Sexual Preferences' 'Smoke' 'Disability'
 'Customer Service' 'Smell' 'Abuse and Rape' 'Autistic' 'Homophobia'
 'Abbey' 'Connectivity' 'Racism' 'Trans' 'Sexual Objects' 'Complaints'
 'Transgender and Sexual Preferences' 'Gender dysphoria' 'Homosexuals'
 'Feminism' 'Mental Illness' 'Nuisance' 'Laptop' 'Refunds' 'Rape culture'
 'Cops' 'Ablessness/Disability' 'Immigration' 'Bug' 'Bathroom'
 'Social Market Economy' 'Mussel' 'Slutship' 'Hygiene' 'Male' 'Sexuality'
 'Household' 'Social Outcast' 'Transphobia' 'Self-harm' 'Murder' 'Judaism'
 'LGBT' 'Transgenderism' 'Hability' 'Trans sexuality' 'Motherhood' 'Radio'
 'Abilities' 'Pedophiles' 'Nutrition' 'Smoking' 'Network'
 'LGBT Sexuality and Sexual Preferences' 'Porn' 'Abuse of Free Speech'
 'Gambling' 'Abnormalities' 'Incompetence' 'Bisexual' 'Nature' 'Hymen'
 'Child molesters' 'Lesbian' 'N' 'Social ill' 'Violence and Criminality'
 'Rape Culture' 'Homosexual' 'Door' 'Cleanliness' 'Sami' 'Sexual violence'
 'Islam' 'Spice' 'Sex' 'Noise' 'Anguish' 'Skin' 'Printer' 'Road' 'Style'
 'Bedbugs' 'Abnormal Sexual Violence' 'Flood' 'Foreskin'
 'Beauty Standards' 'Suicide' 'Quality' 'Police Violence' 'Smelly'
 'Beauty Salon' 'Abnormal/Unusual' 'Insects' 'Hate speech'
 'Domestic Violence' 'Holocaust' 'Breed' 'Animals' 'Eye Health'
 'Hostility' 'Fight back' 'Asylum Seeking' 'Inland Empire' 'Riot'
 'Biology' 'Death' 'Christmas' 'Fishing' 'News' 'Mismatch'
 'Income Inequality' 'Turkeys' 'Pig' 'Language' 'Manipulation' 'Londoners'
 'Trans League' 'Addiction' 'Neighbourhood' 'Aboriginal' 'Skiing'
 'Sexual Orientation' 'Office' 'Hunting' 'Taste' 'Animal Welfare'
 'Wildlife' 'Diversity' 'Hair Color' 'Morality' 'Nurses' 'Species'
 'Abuse and exploitation' 'Grade' 'Infection'
 'All these daffodils are making me sick with hayfever' 'Error' 'Lie'
 'Mobile Network' 'Community Improvement' 'Blindness' 'Autism'
 'Cybersecurity' 'Inclusiveness' 'Sport' 'Keyboard' 'Architecture'
 'Mobile' 'Irritation' 'Parental Responsibility' 'Foot and Spine Problems'
 'COVID19' 'Police' 'Rape and Sexual Assault' 'Hate crimes' 'Cuckery'
 'Irregularity' 'Genetically different' 'Wildlife Park' 'Moral Philosophy'
 'Transportation' 'Pests' 'Cretin' 'Colour' 'Smelly head' 'Recovery'
 'Influencer' 'Substance abuse' 'Pets' 'Coronavirus' 'Asocials'
 'Inbreeding' ' sexuality and sexual preferences' 'Celebrity'
 'Accessibility' 'Immigration and National Policing' 'Hate to be THAT guy'
 'Vegetarian' 'Kitchen' 'Osteoporosis' 'Social Engineering' 'Pregnancy'
 'Sexual Assault' 'Woodpecker' 'Stomach' 'Vampire Infestation' 'Parasites'
 'Heterosexuality' 'Societal Benefit' 'Hair Style' 'Science' 'Spastic'
 'LGBTure' 'Organisation and Team Building' 'Phobia' 'Hapses and Japanese'
 'Animal Husbandry' 'Shipping' 'Slavery' 'Blade' 'Military' 'Swimming'
 'Yoga' 'Gangs' 'Social Services' 'AWS' 'Action' 'Refugees' 'Financial'
 'Cleaning' 'Labor' 'Heart Rate' 'Wealth' 'Home Correction' 'Blender'
 'Segregation' 'Accounting' 'Lying' 'Woodworking' 'Evolution' 'Sinister'
 'Temperature' 'Invasion' 'SFA' 'Self Defence' 'Performance' 'Weight'
 'Reptile' 'Sexual orientation' 'Attack' 'Bias' 'Abnormalcy' 'War Crimes'
 'Soap' 'Cancer' 'Gunshot' 'Clean' 'Resentment' 'Social distancing'
 'Zodiac' 'LGBTURESS' 'Nation' 'Halloween' 'Moral Principles'
 'Homosexuality and Sexual Preferences' 'Family Relations' 'Phone'
 'Disregard' 'LGBT-free zones' 'Goal' 'Scary' 'COVID' 'Refugee Status'
 'Laundry' 'Comms' 'Lazy' 'Business Pitch Proposals' 'Fruits' 'Community'
 'Mussies' 'Game of Thrones' 'Mathematics' 'Fruit' 'Wage' 'Baggage'
 'Food and Agriculture' 'Morning sickness' 'Audio Quality'
 'Transgender and Gay' 'Asocial' 'Psychic' 'Trade' 'Knife and Fork'
 'Paralysis' 'Anti-Semitism'
 'Bullying and targeting attention seekers is my fav hobby' 'Ethics'
 'Bender' 'Color' 'Bulldozing' 'Vampire' 'Mexican' 'Violence and Theft'
 'Abbling' 'Domestic' 'Slang' 'Sleeves' 'Weekend Off' 'Frustration'
 'Nasal Breathing' 'Royalty' 'Kissable Lips' 'Abundance' 'Sadness'
 'Vaginal Health' 'Family Violence' 'Rats' 'Bludgeering'
 'Automotive Industry' 'Erectile Dysfunction' 'Disease' 'LGTB rights'
 'Scamming' 'Fear' 'Homelessness' 'Parental Relationship' 'Citizenship'
 'Queer' 'Food & Beverage' 'Flowers' 'Dental Health' 'Nigger' 'Control'
 'Fighting back' 'Homophobic' 'Population' 'War Crime' 'Smush'
 'Hooliganism' 'Humor' 'Pavement Apes' 'Hair Type'
 'Diversity and Inclusion' 'Bedroom' 'Protection' 'Fitness' 'Travel'
 'Gang' 'Vore' 'Food and Drink' 'State-sponsored racism' 'Corona'
 'Causality' 'Film' 'Scare' 'Left-handed' 'Abra-cording' 'Alcohol' 'LGBT+'
 'Animal Rights' 'Welfare State' 'Migration' 'Sexual Perversion'
 'Military Invasion' 'Looting' 'Abuse of power' 'Medical Profession'
 'Rape · Religion' 'Punishment' 'Access Token' 'Rights' 'Allelopathy'
 'Spasticity' 'Sycophantic' 'Neighborhood' 'Threats' 'Civilisation'
 'Medication' 'Abomination' 'Flag' 'Cervical screening' 'Ship' 'False'
 'Mischief' 'Exercise' 'Self-Care' 'Anti-Fascist' 'Rules' 'Gun Conflict'
 'Divorce' 'Deception' 'Trolling' 'Pest' 'Inclusion' 'Subspecies'
 'Endurance' 'Civil Unrest' 'Hair Loss' 'Noxious' 'Insubordinate'
 'Breastfeeding' 'Aging' 'cuisine' 'Landscape' 'Abemoisility'
 'Phone Calls' 'NPD' 'Generation' 'Predator' 'Alcohol and Weed'
 'Violence against women and victim blaming' 'Antibiotic Resistance'
 'Scent' 'Chaos' 'Gun' 'Famine' 'Inclusivity' 'Skin Treatment'
 'Violence against women' 'Love and cherish' 'Food and Wine' 'Labor Day'
 'Browser' 'Abdominal Pain' 'Rentals' 'Home and Garden' 'Transphobe'
 'Ticks' 'Nuclear Weapons' 'Abnormal Request' 'Haps' 'Cars'
 'Climate change' 'Senses' 'Nationals' 'Abstinence' 'Vision'
 'Drug Dealing' 'School' 'Caste' 'Profession' 'Alcohol and Pub'
 'Road Safety' 'Climate' 'Eye Loss' 'Romania' 'Social Security' 'Home'
 'Mussie' 'Selfishness' 'Dogs' 'Hate and Abomination'
 'Religion and Sexual Preferences' 'Homophobes' 'Abnormal Psychology'
 'Fashion' 'Criminology' 'Fines' 'Zoo' 'Warlord-General' 'Repair' 'Plague'
 'Nursery' 'Hooligans' 'Advertising' 'Bingo' 'Pain' 'Korean'
 'Feral Animals' 'Navigation' 'Farming' 'Mosquito' 'Lighting'
 'Accommodation' 'Location' 'Masks' 'Firefighting' 'Veganism'
 'Bureaucracy' 'Algae' 'Advice' 'Unemployment' 'Vegetables' 'Black Plague'
 'Rent Avoiders' 'Anti-Fascism' 'Pathogens' 'Inflammation' 'Strength'
 'Ignorance' 'Hug' 'Hunger' 'Transblind' 'Domestic Foxes' 'Neighbour'
 'Ectotherm' 'Slacker' 'Birds' 'Waste' 'Road rage' 'Pride' 'Transvestites'
 'Ink' 'Refugee Sentiment' 'English' 'Dysfunction' 'Altered'
 'Native Americans' 'Child Protection' 'Cervical Cancer' 'Pavement'
 'Islamic jihadists' 'Islamist Terrorism' 'Satanism' 'Nation-Building'
 'Combat' 'Insurance' 'Fraud' 'Ableness' 'Hunting Season'
 'Culture and Values' 'Peace' 'Coughing' 'Abnormal Personality'
 'Diplomacy' 'Sexual assault' 'Yard Work' 'Tattoo'
 'Whose behind miley cyrus antics ?' 'Civil Rights' 'Media' 'Adrenaline'
 'Nationalism' 'Jihad' 'Memorial' 'Hate Group' 'Firearm' 'Malignity'
 'Integrity' 'Interview' 'Social Consequences' 'Revolution' 'Disaster'
 'Populism' 'Waffen-SS' 'Infrastructure' 'Marriage and Family'
 'Space Exploration' 'Freedom of expression' 'Moral' 'Currency'
 'Inolerance' 'Social Defects' 'Gun-related incidents' 'Freedom of Speech'
 'Military Readiness' 'Social Benefits' 'Culinary Art' 'Nuclear Waste'
 'Terror org' 'Sickness' 'Identity' 'Cuck' 'NuclearCheckmate' 'Potato'
 'Asia' 'Warning' 'Family Law' 'Sexual abuse' 'Political Establishment'
 'Road Traffic' 'Nationalsocialism' 'LGBTQBBQ' 'Wage and Poverty'
 'Justice and Immigration' 'Karma' 'Viking' 'Gun Rights'
 'Moral Superiority' 'Marriage Equality' 'Attention' 'Quality Standards'
 'Sweet Tea' 'Networking' 'Sexual harassment' 'State Election'
 'Social Gatherings' 'Uniforms' 'Hate group' 'Home Security'
 'National Security' 'Border Dispute' 'News Media' 'Visa over-stayers'
 'Internationalism' 'Warship' 'Blood Donation' 'Heritage'
 'Antifa Violence' 'Trade Promotion Authority' 'Marriage and Constitution'
 'Fire Chief' 'Civil War' 'Fighting' 'Food shelter' 'Injustice'
 "Asperger's" 'Comments' 'Republic' 'Bankruptcy' 'Back Pain' 'Bow'
 'Christmas Tree' 'Islamophobia' 'Military Contracts' 'Homicides'
 'Political Weapons' 'Anti-fascist' 'Name' 'Geopolitics' 'Application'
 'Community Violence' 'Threat of jihad' 'Victory' 'Marxism' 'Negative'
 'Jail' 'Conference' 'Abuse of Rights' 'Huntington Beach'
 'National Defense' 'Petrol and Diesel' 'Storm' 'Justice and Law' 'Spider'
 'National Socialism' 'Protest' 'Social Media Censorship'
 'Social Extremism' 'Grocery shopping' 'Legal Argument' 'Dyslexia'
 'Rebellion' 'Wedding Cakes' 'Violence and Rhetoric' 'Animal Control'
 'Jihadis' 'Revenge' 'Corruption and Incompetence' 'Regulation' 'Funding'
 'Revolutionary Folk Hero' 'Geopolitical' 'Wisdom' 'Moral Status' 'Art'
 'Cardiac arrest' 'Cyberattack' 'Heroism' 'Mental Disorder' 'Card Game'
 'Threat to Public Safety' 'Crocodilian' 'Gun Ownership'
 'Sexual immorality' 'Drug Resistant Diseases' 'Leg' 'Crime and Theft'
 'Nuclear Weapon' 'immigration status' 'Bitch' 'Rape and Violence' 'Homos'
 'Insecurity' 'Lifestyle' 'Vengeance' 'Rape kink' 'Violence and Terror'
 'Pervert' 'Hysteria' 'Insurrection' 'Warfare' 'Moral Values'
 'Marriage and Relationships' 'Sex crime arrests' 'Refugees and Welcome'
 'Homelife' 'Hysterical' 'Rape and Murder' 'Frage' 'Celiac' 'Singing'
 'Discrimination' 'Rape and Sexual Violence' 'Welfare and Government'
 'Segregation and Discrimination' 'Irradiation'
 'Violence and Sexual Abuse' 'Violence and Immorality' 'Military Strategy'
 'Submission' 'Homosexuality and Bisexuality' 'Criminality' 'Nuclear War'
 'Abnormal Sexuality' 'Gun violence' 'Security Risk' 'Political Ideology'
 'All' 'Persecution' 'Abbleness/Disability' 'Virus' 'Events' 'Nukes'
 'Hierarchy' 'Scouting' 'Health and Wellness' 'Community Resistance' 'URL'
 'Knife blocks' 'Morals' 'Sporting Goods' 'Reception' 'Photography'
 'Maintenance' 'Anime' 'Vehicle' 'Introversion' 'Blood' 'Blades'
 'Science Fiction' 'Restaurant' 'Knees' 'Scars' 'War Zone' 'Skin Tone'
 'Irish' 'Knife Set' 'Driver' 'Art Institute of Chicago' 'Beach'
 'Rape and Sexual Abuse' 'City' 'Music Video' 'History Channel'
 'Vehicle Damage' 'Crimea' 'Eye Color' 'University' 'Computer Programming'
 'Sexual and Gender Identity' 'Science and Technology' 'Automotive'
 'Burglary' 'Civilization' 'Motorcycle' 'Holiday' 'Stress Relief' 'Pack'
 'Reputation' 'Fantasy' 'Social Gathering' 'Churchill' 'Donation'
 'Food poisoning' 'Sunglasses' 'Family Camping' 'Youth'
 'Music and Education' 'Coal' 'Alpine' 'Burrito Explosion' 'Gunsmithing'
 'Purchase' 'Social Skills' 'Loss' 'Social Terrorist' 'Paradise' 'Bowmen'
 'Mortality' 'Vacation' 'Nuclear Reactor' 'Date' 'Native American'
 'Iniquity' 'Logic' 'Adventure' 'Moral Direction' 'Blood Geyser'
 'Energy Sector' 'Security Procedures' 'Museum' 'Social terrorizers'
 'Military Strength' 'News and Articles' 'Misadventure' 'Self-improvement'
 'Blood Group' 'Physical Injury' 'Assault and Battery' 'CZE' 'Fish'
 'Books' 'Food and Dining' 'Executive Board' 'Human Rights Violations'
 'Blogs' 'Robbery' 'Video' 'Society' 'Traffic Lite' 'Grunge rock' 'Wind'
 'Sexual orientation and sexual preferences' 'Mercury' 'Breakfast'
 'Abuse of Benefits' 'Holisme' 'Liquor Stores' 'Cute babies'
 'Strength and Fitness' 'Refugee Crisis' 'Ram' 'Surname' 'Moderation'
 'Welding' 'Civil Rights Movement' 'Values' 'Cash' 'Safety and Security'
 'Imports' 'Gene' 'Skinhead Rock and Roll' 'Election Fraud'
 'Attack on a christian girl' 'Audition' 'Parking' 'Bowel' 'Refugee'
 'Band' 'Skill' 'Work' 'Auction' 'Illegal Activities' 'Time off work'
 'Cycling' 'Greek' 'Diet' 'Fire' 'Nuclear Disaster' 'Rape Survivors'
 'Adjective' 'Lips' 'Motivation' 'Employment' 'Website' 'Statistics' 'Bar'
 'Military History' 'Communism' 'Maturity' 'Weekend' 'Thank you'
 'Gun/Weapon' 'Research' 'Abuse of Benefits System' 'Memory' 'Brewery'
 'Prophecy' 'England' 'Fire and Protection' 'Home Decor' 'Rehabilitation'
 'Manufacturing' 'Distribution' 'Authenticity' 'Mexico' 'Hero'
 'Gun Training' 'Attitude' 'Recommendation' 'Retailer collapse'
 'Snow boarder' 'Cardiovascular Disease' 'Dance' 'Ebola' 'Child Safety'
 'Automobile' 'Genetics' 'Gun Possession' 'Video Opening' 'Rural Cabin'
 'Welcome' 'Crafting' 'Time' 'Social Club' 'Smile' 'Home Burglary'
 'Childcare' 'Nose' 'Legal Services' 'Home Defense'
 'Sexual violence and terrorism' 'Genocide' 'Modern' 'Nuclear Plant'
 'Fertility' 'Metal' 'Film Companion' 'Language Acquisition'
 'Physical Disability' 'Hate Symbol' 'Tsunami' 'Poland' 'Ultrasound'
 'Decoration' 'Matchbooks' 'Christmas Music' 'Nuclear' 'Hip Hop'
 'Homework' 'Children' 'War and Conflict' 'Sperm' 'Home and Land'
 'Cyclone' 'Sugar' 'Computer' 'Hump Back' 'School officials' 'Audio Book'
 'Dance Music' 'Fitness Center' 'Animal Planet' 'Icelandic' 'Self Defense'
 'Audio/Video' 'Movie' 'Weapon' 'Cable Access' 'Skinheads' 'Amazon'
 'Documentary' 'Reading'
 'Sexual assault suspect caught on cellphone video' 'Socialization'
 'Sexual harassment and assault' 'Rape Victim' 'Home Care' 'Engineering'
 'Christmas Lights' 'Emergency Services' 'Legal Advice' 'nationality'
 'Homicide' 'State' 'Disagreement' 'Programming' 'Country'
 'Grammar and Spelling' 'Self-Love' 'Distance' 'Rodeo' 'Nuclear Explosion'
 'Caregiving' 'Alone' 'YouTube' 'Political Violence' 'Pagan' 'Gangster'
 'Information Distribution' 'Cult of Piece' 'Service' 'Newsletter'
 'Missing Person' 'Health and Fitness' 'Galaxy' 'Assessment' 'River'
 'Solar Flare' 'Horror' 'Self-love' 'Miscellaneous' 'Nebulae'
 'Phone Number' 'Halloween costumes' 'Tattoos' 'Packing' 'Spelling' 'HIV'
 'Regret' 'Emergency' 'Abblness/Disability' 'Spiritual Awakening'
 'Structural' 'Stem Cell Research' 'Fruits and Vegetables' 'Burrito'
 'Small' 'Culture and Heritage' 'Period' 'Cruise' 'Promotion' 'London'
 'Material' 'Hacking' 'HIV/AIDS' 'Loan' 'Hereditary' 'Metal and Alloys'
 'Family History' 'Driving' 'Rural towns' 'Awards' 'Ragnar Saga'
 'Archaeology' 'Executive Director' 'Foot loss' 'Food Safety'
 'Social Issue' 'Social Sciences' 'Sticker techniques' 'Video Clip'
 'Infectious Disease' 'Death Mask' 'Damage' 'Military Aid' 'Finances'
 'Home and Kitchen' 'Stadium' 'Chromosome' 'Mod' 'Signature' 'Ice Cream'
 'Peaceful Warrior' 'Multicultural Enrichment' 'Family Heritage'
 'Child Development' 'Welcoming' 'Welfare Mother' 'Moustache'
 'Sexual and Sexual Violence' 'Taco Bell' 'Ghetto' 'Real Estate'
 'Gun Prices' 'Wake up' 'Probation Violation' 'DNA' 'Social Influence'
 'Resignation' 'Danger' 'Brain Size' 'Debt' 'Schoolbook' 'Bmx Bikes'
 'Food Production' 'Sentiment' 'Cossacks' 'Stocks' 'Excitement'
 'Sports and Leisure' 'Rent' 'Police and Security' 'Cosmic Phenomena'
 'Welfare Checks' 'Organ Transplantation' 'CIA' 'Algebra' 'Sexual dancing'
 'Strategy' 'Call for action' 'Reviews' 'Fatigue' 'Wildlife Protection'
 'Camping' 'Relationship Issues' 'Social Propaganda' 'Animation'
 'Pedophile' 'Truck' 'Word problems' 'Eye' 'Market' 'Crude Oil Production'
 'Gun Show' 'Bookseller' 'Nervousness' 'Punk' 'Election Status' 'Accuracy'
 'Socializing' 'Sports and Recreation' 'Hunting knives' 'Life' 'Motorrad']

## Normalize all target values to obtain uniform Data Frames

In [8]:
import re

def normalize_target(x):
    if pd.isna(x):
        return "none"

    x = str(x).strip().lower()
    x = re.sub(r"\s+", " ", x)

    if x in ["none", "unknown", "irrelevant", "miscellaneous", "all", "n"]:
        return "none"

    # Race / ethnicity / racism / specific ethnic references
    if any(k in x for k in [
        "race", "racism", "skin tone", "skin color", "colour", "color",
        "native american", "aboriginal", "mexican", "korean", "irish",
        "japanese", "sami", "ghetto", "nigger"
    ]):
        return "race"

    # Religion
    if any(k in x for k in [
        "religion", "islam", "judaism", "christian", "jihad",
        "islamophobia", "holocaust", "anti-semitism", "satanism"
    ]):
        return "religion"

    # Gender / women / feminism
    if any(k in x for k in [
        "gender", "male", "female", "women", "woman", "feminism",
        "motherhood", "pregnancy", "breastfeeding"
    ]):
        return "gender"

    # Sexual orientation / LGBTQ+ / trans
    if any(k in x for k in [
        "sexual", "homosexual", "lgbt", "queer", "trans",
        "bisexual", "lesbian", "homophobia", "transphobia",
        "gay", "heterosexual"
    ]):
        return "sexual_orientation"

    # Immigration / refugees / asylum
    if any(k in x for k in [
        "immigration", "migration", "refugee", "asylum",
        "visa", "border"
    ]):
        return "immigration_status"

    # Nationality / nation / nationalism
    if any(k in x for k in [
        "nationality", "nationals", "citizenship", "nationalism",
        "country", "england", "romania", "poland", "europe"
    ]):
        return "nationality"

    # Disability / ableism / mental disability
    if any(k in x for k in [
        "disability", "ableness", "abless", "abelness", "abbling",
        "autism", "autistic", "blindness", "paralysis", "spastic",
        "dyslexia", "asperger"
    ]):
        return "disability"

    # Social class / poverty / welfare / homelessness
    if any(k in x for k in [
        "class", "poverty", "homeless", "welfare", "income",
        "wealth", "unemployment", "rent avoiders"
    ]):
        return "class"

    # Politics / ideology / government
    if any(k in x for k in [
        "politic", "government", "election", "democracy", "socialism",
        "communism", "marxism", "antifa", "fascism", "national socialism",
        "populism", "brexit"
    ]):
        return "politics"

    # Violence / crime / threats / war / terrorism / weapons
    if any(k in x for k in [
        "violence", "threat", "terror", "war", "crime", "criminal",
        "rape", "murder", "homicide", "abduction", "assault",
        "gun", "weapon", "knife", "gang", "attack", "riot",
        "nuclear", "genocide", "combat", "military"
    ]):
        return "violence"

    # Health / medical / mental health / substance
    if any(k in x for k in [
        "health", "mental", "illness", "disease", "medical",
        "cancer", "diabetes", "covid", "coronavirus", "virus",
        "suicide", "self-harm", "addiction", "substance", "alcohol"
    ]):
        return "health"

    return "other"

In [9]:
for df in all_dfs:
    df["target"] = df["target"].apply(normalize_target)

## Creating the Ultimate Dataset

In [10]:
df_Ultimate_explicit_train = pd.concat([df_AbuseEval_explicit_train, df_DynaHate_explicit_train, df_Implicit_Hate_Corpus_explicit_train, df_IsHate_explicit_train], ignore_index=True)
df_Ultimate_explicit_test = pd.concat([df_AbuseEval_explicit_test, df_DynaHate_explicit_test, df_Implicit_Hate_Corpus_explicit_test, df_IsHate_explicit_test], ignore_index=True)
df_Ultimate_implicit_train = pd.concat([df_AbuseEval_implicit_train, df_DynaHate_implicit_train, df_Implicit_Hate_Corpus_implicit_train, df_IsHate_implicit_train], ignore_index=True)
df_Ultimate_implicit_test = pd.concat([df_AbuseEval_implicit_test, df_DynaHate_implicit_test, df_Implicit_Hate_Corpus_implicit_test, df_IsHate_implicit_test], ignore_index=True)

In [11]:
#df_Ultimate_explicit_train.to_csv("ultimate_explicit_train.csv", index=False)
#df_Ultimate_explicit_test.to_csv("ultimate_explicit_test.csv", index=False)
#df_Ultimate_implicit_train.to_csv("ultimate_implicit_train.csv", index=False)
#df_Ultimate_implicit_test.to_csv("ultimate_implicit_test.csv", index=False)

In [12]:
df_Ultimate_explicit = pd.concat([df_Ultimate_explicit_train, df_Ultimate_explicit_test], ignore_index=True)
df_Ultimate_implicit = pd.concat([df_Ultimate_implicit_train, df_Ultimate_implicit_test], ignore_index=True)
df_Ultimate_combined = pd.concat([df_Ultimate_explicit, df_Ultimate_implicit], ignore_index=True)

In [13]:
#df_Ultimate_explicit.to_csv("ultimate_explicit.csv", index=False)
#df_Ultimate_implicit.to_csv("ultimate_implicit.csv", index=False)
#df_Ultimate_combined.to_csv("ultimate_combined.csv", index=False)

In [14]:
df_Ultimate_implicit["hate_label"].value_counts()

hate_label
1    56348
0    52555
Name: count, dtype: int64

## Creating the Gab Test Dataset

In [15]:
df_GAB_raw = pd.read_csv("GabHateCorpus_annotations.tsv", sep="\t")

In [16]:
df_GAB_raw.head(10)

,ID,Annotator,Text,Hate,HD,CV,VO,REL,RAE,SXO,GEN,IDL,NAT,POL,MPH,EX,IM
0,27044,4,Ah the PSYOPS antifa crew is back. That’s how I know we are winning.,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,27044,15,Ah the PSYOPS antifa crew is back. That’s how I know we are winning.,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,27044,10,Ah the PSYOPS antifa crew is back. That’s how I know we are winning.,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,27044,8,Ah the PSYOPS antifa crew is back. That’s how I know we are winning.,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,27045,4,Get the new Android app update released today here: https://gab.ai/about/android,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,27045,10,Get the new Android app update released today here: https://gab.ai/about/android,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,27045,8,Get the new Android app update released today here: https://gab.ai/about/android,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,27046,4,Study: Google Pushes Liberal News in Top 5 Search Suggestions https://www.newsbusters.org/blogs/techwatch/corinn...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,27046,15,Study: Google Pushes Liberal News in Top 5 Search Suggestions https://www.newsbusters.org/blogs/techwatch/corinn...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,27046,10,Study: Google Pushes Liberal News in Top 5 Search Suggestions https://www.newsbusters.org/blogs/techwatch/corinn...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
import random

rng = random.Random(42)

def gab_style(row):
    if row["EX"] >= 0.5:
        return 1  # explicit
    if row["IM"] >= 0.5:
        return 0  # implicit
    return np.nan

def gab_targets_all(row):
    target_cols = {
        "RAE": "race",
        "NAT": "nationality",
        "GEN": "gender",
        "REL": "religion",
        "SXO": "sexual_orientation",
        "IDL": "politics",
        "POL": "politics",
        "MPH": "health",
    }

    active = [
        canonical
        for col, canonical in target_cols.items()
        if row.get(col, 0) == 1
    ]

    if row.get("CV", 0) == 1:
        active.append("violence")

    if not active:
        if row["Hate"] == 1:
            return ["other"]
        else:
            return ["none"]

    return list(set(active))  # remove duplicates

In [18]:
df_GAB = pd.DataFrame()
df_GAB["text"] = df_GAB_raw["Text"]
df_GAB["hate_label"] = df_GAB_raw["Hate"].astype(int)
df_GAB["style"] = df_GAB_raw.apply(gab_style, axis=1)
df_GAB["target_list"] = df_GAB_raw.apply(gab_targets_all, axis=1)
df_GAB["target_conf"] = 1.0

# Only keep examples with known style
df_GAB_all = df_GAB.copy() # dataset used for text and hate label only
df_GAB = df_GAB.dropna(subset=["style"])
df_GAB["style"] = df_GAB["style"].astype(int)

# Clean text column
df_GAB = df_GAB.dropna(subset=["text"])
df_GAB_all["text"] = df_GAB_all["text"].astype(str)
df_GAB["text"] = df_GAB["text"].astype(str)

In [19]:
df_GAB.head(10)

,text,hate_label,style,target_list,target_conf
14,"#Breaking: Claiming bias against conservatives, @FreedomWatchUSA has filed a class action lawsuit against Google, Facebook, Instagram, Twitter, and Apple.",1,0,[politics],1.0
16,"“These [companies] are run by sociopaths,” he said. “These people are complete narcissists. These people ought to be controlled, they ought to be regulated.” At one point during the phone call, Bannon said, “These people are evil.' https://www.vanityfair.com/news/2018/08/steve-bann...",1,1,"[nationality, politics]",1.0
54,"Report: Google A.I. Is ‘Biased’ Against Gay People, Jews http://www.breitbart.com/tech/2017/10/26/report-go...",1,1,"[sexual_orientation, religion]",1.0
67,"Except, perhaps, to #SmugLiberal awards ceremonies...or maybe out back to shoot 'em. #SmugHollywoodTypes #Hollywood #JimmyKimmel #Trump #Hannity #Homophobic #Twitter #Twatter #OutBackToShootEm",1,1,"[violence, politics]",1.0
118,'Who’s paying your salary? The Italians who live here? Or the people getting off boats tomorrow morning?' —Matteo Salvini scolds Khalid Chaouki in a heated debate. https://youtu.be/F1N5QLmzCQA #Mastrangelo #Salvini #Italy #gimmegrants #,1,0,[nationality],1.0
132,#GabBrasil an enterprising capitalist might do well setting up an online course/forum teaching Portuguese to Deplorable US Patriots. And/or vice versa... Just saying. 😎,1,1,[nationality],1.0
194,Faggot. https://archive.fo/Kb0YP#selection-457.0-1061.1,1,1,[sexual_orientation],1.0
197,Faggot. https://archive.fo/Kb0YP#selection-457.0-1061.1,1,1,[sexual_orientation],1.0
243,"An inflated example of gesture politics is all it is, and a pathetic reminder of how many on the left have descended to the same level as the target of their protest. https://medium.com/@sd_saurav/the-trump-blimp-woul...",1,1,[politics],1.0
245,My interview with the one and only @GeertWilders on #MuhammadCartoonContest sent your entry in yet?? https://medium.com/@sd_saurav/why-geert-wilders-is...,1,0,[religion],1.0

In [20]:
df_GAB.head(10)

,text,hate_label,style,target_list,target_conf
14,"#Breaking: Claiming bias against conservatives, @FreedomWatchUSA has filed a class action lawsuit against Google, Facebook, Instagram, Twitter, and Apple.",1,0,[politics],1.0
16,"“These [companies] are run by sociopaths,” he said. “These people are complete narcissists. These people ought to be controlled, they ought to be regulated.” At one point during the phone call, Bannon said, “These people are evil.' https://www.vanityfair.com/news/2018/08/steve-bann...",1,1,"[nationality, politics]",1.0
54,"Report: Google A.I. Is ‘Biased’ Against Gay People, Jews http://www.breitbart.com/tech/2017/10/26/report-go...",1,1,"[sexual_orientation, religion]",1.0
67,"Except, perhaps, to #SmugLiberal awards ceremonies...or maybe out back to shoot 'em. #SmugHollywoodTypes #Hollywood #JimmyKimmel #Trump #Hannity #Homophobic #Twitter #Twatter #OutBackToShootEm",1,1,"[violence, politics]",1.0
118,'Who’s paying your salary? The Italians who live here? Or the people getting off boats tomorrow morning?' —Matteo Salvini scolds Khalid Chaouki in a heated debate. https://youtu.be/F1N5QLmzCQA #Mastrangelo #Salvini #Italy #gimmegrants #,1,0,[nationality],1.0
132,#GabBrasil an enterprising capitalist might do well setting up an online course/forum teaching Portuguese to Deplorable US Patriots. And/or vice versa... Just saying. 😎,1,1,[nationality],1.0
194,Faggot. https://archive.fo/Kb0YP#selection-457.0-1061.1,1,1,[sexual_orientation],1.0
197,Faggot. https://archive.fo/Kb0YP#selection-457.0-1061.1,1,1,[sexual_orientation],1.0
243,"An inflated example of gesture politics is all it is, and a pathetic reminder of how many on the left have descended to the same level as the target of their protest. https://medium.com/@sd_saurav/the-trump-blimp-woul...",1,1,[politics],1.0
245,My interview with the one and only @GeertWilders on #MuhammadCartoonContest sent your entry in yet?? https://medium.com/@sd_saurav/why-geert-wilders-is...,1,0,[religion],1.0

In [21]:
from collections import Counter

def majority_label(series):
    values = series.dropna().tolist()
    if len(values) == 0:
        return np.nan
    return Counter(values).most_common(1)[0][0]

def majority_target(series):
    all_targets = []

    for targets in series:
        all_targets.extend(targets)

    if len(all_targets) == 0:
        return "none"

    counts = Counter(all_targets)
    max_count = max(counts.values())

    top_targets = [k for k, v in counts.items() if v == max_count]

    # if multiple top targets, return random choice among them (tie-break)
    return rng.choice(top_targets)

df_GAB_agg = (
    df_GAB
    .groupby("text", as_index=False)
    .agg(
        avg=("hate_label", "mean"),
        hate_label=("hate_label", lambda x: int(x.mean() >= 0.5)),
        style=("style", majority_label),
        target=("target_list", majority_target),
        target_conf=("target_conf", "mean"),
    )
)

df_GAB_agg["style"] = df_GAB_agg["style"].astype(int)
df_GAB_agg["target_conf"] = 1.0

In [22]:
df_GAB_final = df_GAB_agg[
    ["text", "hate_label", "style", "target", "target_conf"]
].copy()

In [23]:
#df_GAB_final.to_csv("gab_combined.csv", index=False)

In [24]:
df_GAB_explicit = df_GAB_final[df_GAB_final["style"] == 1].copy()
df_GAB_implicit = df_GAB_final[df_GAB_final["style"] == 0].copy()

In [25]:
#df_GAB_explicit.to_csv("gab_explicit.csv", index=False)
#df_GAB_implicit.to_csv("gab_implicit.csv", index=False)

In [26]:
df_GAB_all.drop(columns=["style", "target_list", "target_conf"], inplace=True)
df_GAB_all_agg = df_GAB_all.groupby("text", as_index=False).agg(
    hate_label=("hate_label", lambda x: int(x.mean() >= 0.5))
)

In [27]:
#df_GAB_all_agg.to_csv("gab_only_hate_label.csv", index=False)

## Creating the SBIC test dataset

In [28]:
df_SBIC_raw = pd.read_csv("SBIC.v2.trn.csv")

In [29]:
np.set_printoptions(threshold=np.inf)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)
df_SBIC_raw['targetMinority'].unique()

array([nan, 'black folks', 'women', 'black women', 'conservatives',
       'republicans', 'ugly folks', 'gay men', 'poor folks',
       'lesbian women', 'overweight/fat folks', 'white folks',
       'black folks, white folks', 'AAP',
       'folks with mental illness/disorder, mentally disabled folks',
       'mentally disabled folks', 'folks with mental illness/disorder',
       'latino/latina folks', 'lesbian women, gay men', 'muslim folks',
       'jewish folks, muslim folks', 'physically disabled folks',
       'women, gay men', 'black folks, white women', 'white females',
       'men',
       'gay men, trans women, trans men, bisexual women, bisexual men',
       'Islam', 'assault victims', 'physically disabled folks, fat folks',
       'Southerners', 'asian folks', 'rednecks', 'jewish folks',
       'rape victims',
       'lesbian women, gay men, trans women, trans men, bisexual women, bisexual men',
       'native american/first nation folks', 'immigrants', 'White people',
       'women, men', 'liberals', 'old folks', 'smokers', 'Mormon folks',
       'skinny folks', 'old ladies', 'breast size',
       'muslim folks, arabic folks', 'red heads',
       'sexual assault victims', 'white people', 'arabic folks',
       'liberals, conservatives', 'white girls', 'White', 'Virgos',
       'mexican', 'black folks, latino/latina folks',
       'assault victims, rape victims', 'indigenous folks',
       'light skinned black folks', 'Feminists', 'feminists',
       'Rural people', 'trans women, trans men',
       'asian folks, latino/latina folks', 'everyone',
       'assault victims, Sexual assault victims', 'people with OCD',
       'Worcester', 'Rednecks', 'Child sexual assault victims', 'India',
       'shiv sena political party', 'Gun enthusiasts', 'Syrians',
       'fascists', 'indian folks', 'Americans', 'whites', 'cops',
       'mass shooting victims', 'southerners', 'young people',
       'Jehovah witnes', 'gays', 'trans men', 'Arab folks',
       'mexican folks', 'Non - binary', 'liberals, Democrats', 'refugees',
       'Trump supporters', 'non-white folks', 'women, trans men',
       'christian folks', 'liberals, feminists', 'Islamic', 'punjab',
       'pakistani folks', 'high school students', 'Indian folks',
       'conservatives, Republicans', 'muslim folks, hindu folks',
       'sex trafficking victims', 'suicide victims', 'Men', 'islam',
       'islamics', 'Africa', 'Syria', 'women, lesbian women', 'americans',
       'car accident victims', 'young folks', 'England', 'all pocs',
       'Canada', 'Korea', 'Amsterdam', 'teenagers', '18 year olds',
       'Syrian rebels', 'prisoners', 'Holocaust victims', 'millenials',
       'people from Abu Dhabi', 'Millennials', 'Younger people',
       'younger genereration', 'dominican women', 'dominican', 'manners',
       'Democrats', 'women, lesbian women, feminists', 'gamers',
       'syrians', 'syrian', 'independents/libertarians', 'syrian folks',
       'physically disabled folks, mentally disabled folks', 'Gemini',
       'conservatives, alt right', 'politicians', 'syrians, russians',
       'Syrians/Russians', 'syrian and russian folks', 'Kids',
       'liberals, democrats', 'furries',
       'black folks, asian folks, latino/latina folks, native american/first nation folks',
       'OD victims', 'trump supporters', 'Indians', 'assad region',
       'philistine', 'South Asia', 'lesbian women, bisexual women',
       'vegans', 'russins', 'autistic folks', 'Antifa', 'anti-vaxxers',
       'Russia', 'atheists', 'poor folks, conservatives',
       'well off folks', 'south africans',
       'everybody not in the US (foreigners)', 'aborigines',
       'aboriginal folks', 'aboriginal', 'chinese folks', 'Welsh',
       'middle eastern people', 'people from india',
       'folks with physical illness/disorder, folks with mental illness/disorder',
       'holocaust victims', 'pregnant folks', 'Parents',
       'assault victims, kidnap victim',
       'folks with physical illness/disorder',
       'child sexual assault victims', 'harassment victims',
       'Irish folks', 'cancer victims', 'Indian', 'indians', 'Africans',
       'pedophilia victims',
       'physically disabled folks, folks with physical illness/disorder',
       'war crime victims', 'victims of racial and homophobic attacks',
       'child molesters', 'japanese people', 'prostitutes',
       'saudi arabian folks', 'africans', 'rural/ country folks',
       'Venezuela', 'syrian women', 'children', 'terrorism victims',
       'mass shooting victims, terrorism victims', 'Ethiopian', 'France',
       'french women', 'old folks, seniors', 'Ethiopia', 'ethiopia',
       'Ethiopians', 'child rape victims', "people who've had abortions",
       'African folks', 'african folks', 'African kids', 'Young people',
       'murder victims', 'midget', 'shorts folks', 'Cancer patients',
       'autistic', 'police offices', 'Fathers', 'abortion',
       'physically disabled folks, folks with physical illness/disorder, folks with mental illness/disorder, mentally disabled folks',
       'women who have had abortions', 'people who have had abortions',
       'aboriginals', 'pregnant teenagers', 'Ethiopian folks', 'uncles',
       'victims of rape and murder', 'Catholic priests',
       'genocide victims', 'Refugees',
       'Victims of poverty and starvation', 'British',
       'immigrants, Mexicans', "Gypsy's", 'Somalia', 'somalia',
       'mexicans', 'American South', 'Ethiopian foods',
       'latino/latina folks, arabs', 'black folks, asian folks',
       'immigrants, mexican folks', 'Vegans', 'Mexican folks', 'Mexicans',
       'orphans', 'muslim folks, refugees', 'Japanese', 'Japanese folks',
       'trans women', 'white men', 'victims of domestic violence',
       'Ethiopian people', 'catholics', 'north koreans', 'russian people',
       'black folks, asian folks, brown/asian people',
       'Southern people, from Alabama USA', 'blondes', 'Nigerian people',
       'Pakistani', 'tragedy victim', 'accident victims', 'Emo folks',
       'Etheopia', 'disabled people', 'poor folks, Africa',
       'young children', 'Bombing victums', 'African children',
       'Religion', 'Arabian', 'french people',
       'people who self-harm/are suicidal', 'police',
       'violent accidental death victims', 'young kids',
       'people with dwarfism', 'American Southerners', 'babies',
       'women, lesbian women, bisexual women, all feminists', 'redneck',
       'southerners from the United States', 'cancer patients',
       'Young kids', 'Oraphans', 'sex abuse victims', 'porn stars',
       'Mexico', 'germans', 'muslim folks, Japanese folks',
       'arabic folks, Japan', 'arabic folks, japanese', 'Suicide victims',
       'fire victims', 'trans women, trans men, feminists', 'democrats',
       'auto accident victims', 'middle-eastern folks', 'Jamaicans',
       'lesbian women, gay men, Vegetarians',
       'assault victims, Holocaust victims', 'priests', 'emo', 'muslims',
       'nonbinary folks', 'African', 'deaf and blind people',
       'Jewish people', 'assault victims, pedophilia victims', 'kids',
       'Chinese people', 'polish folks', 'polish people', 'Polish',
       'minors', 'rural people', 'Jews', 'Thailand', 'Thai',
       'trans folks', 'ethiopians', 'suicide', 'Vietnam', 'Pakistan',
       'Orphans', 'Domestic abuse victims', 'Jewish victims',
       'sex assault victims',
       'lesbian women, gay men, trans women, trans men', 'africa',
       'murder victim families', 'somalian', 'girls and boys.',
       'sexual assault survivors', 'greek', 'Greeks', 'femnists',
       'black africans', 'Child murder victims', 'Chinese folks',
       'Parents of stillborn infants', 'Vietnamese',
       'jewish folks, Buddhists', 'ethiopens',
       'assault victims, harassment victims', 'women, trans women',
       'korean folks', 'child molestation victims', 'minor girls',
       '911 victims', 'Holocaust Victims', 'lgbt',
       'jewish folks, muslim folks, christian folks', 'white poor people',
       'communists', 'Homicide victims', 'mass suicide victims',
       'Spanish', 'climate disaster victims', 'Japanese folk',
       'all disabled folks', 'Italians', 'italian folks', 'Somalian',
       'Somolians', 'Somalians', 'islamic folks', 'ethipian folks',
       'blind people', 'pedophilia', 'Africa/Middle East',
       'middle easterners', 'pakastani...middle eastern',
       'illegal immigrants', 'trans folk', 'holocaust survivors',
       'jewish folks, muslim folks, arabic folks', 'thai folks',
       'Thai folks', 'terrorism victims, assault victims', 'Malaysia',
       'japanese', 'Middle eastern people', 'afghan', 'teen moms',
       'Catholic', 'Pakistanis', 'pakistans', 'Japanese people', 'Japan',
       'kids with cancer', 'gay people', 'jewish folks, jamaican folks',
       'UK people', 'latino/latina folks, jewish', 'child rape victim',
       'nuclear victims', 'bullimacs/anorexics', 'mexicn folks',
       'alabama people', 'southern united states',
       'natural disaster victims', 'Cops',
       'mass shooting victims, assault victims', 'Mongolian',
       'autistic people', 'middle eastern folks', 'Middle easterns',
       'middle eastern', 'HIV positive', 'Poland', 'Necrophilia victims',
       'women, lesbian women, bisexual women', 'thai', 'North Koreans',
       'North koreans', 'animal rights advocates', 'abused children',
       'greeks', 'greek folks', 'child abuse victims',
       'folks with down syndrome', 'Sex workers', 'French folks',
       'Palestinians', 'Islamic folks', 'japanese folks',
       'Kidnap/violence/murder victims', 'Holocaust survivors',
       'War victims', 'vietnamese folks',
       'health related tragedy victims', 'Molestation Victims',
       'chinese people', 'syria', 'Texans', 'albanians', 'Irish',
       'Disaster', 'chernobyl victims', 'the holocaust', 'pakistani',
       'Italian people', 'Pakistani, Islamic', 'LGBT Community',
       'scientologists', 'white', 'All colored races', 'Cancer victims',
       'veterans', 'marines', 'assault victims, abuse victims',
       'assault victims, Child sexual assault victims',
       'Holocaust victims and black victims of slavery', 'Southern US',
       'irish folks', 'Pearl Harbor victims',
       'women, lesbian women, trans women, bisexual women',
       'car crash victims', 'mexican people', 'pro-life advocates',
       'black folks, Mexican folks', 'Brazilians', 'Brazillian folks',
       'physically disabled folks, folks with mental illness/disorder, mentally disabled folks',
       'Polish folks', 'muslim folks, feminist', 'homeless',
       'genital mutilation victims', 'mutilation victims',
       'black folks, Ethopians',
       'assault victims, child molestation victims', 'South USA',
       'Venezuelans', 'Arabic folks', 'african women', 'anorexic folks',
       'arab folks', 'arabian folks', 'Domestic abuse', 'deaf folks',
       'Young boys', 'slave victims',
       'children who have been sexually assaulted',
       'Middle East; Afghanistan', 'environmental victims', 'death',
       'folks with mental illness/disorder, Self-harming people',
       'Caucasians', 'any non-white race', 'Car crash victims.',
       'Holocaust', 'mass accident victims', 'southern folks',
       'women who have had an abortion', 'incest victims', 'seniors',
       'woman with small breasts',
       'black folks, latino/latina folks, native american/first nation folks',
       'physically disabled folks, folks with mental illness/disorder',
       'Children', 'mass accident', 'Childhood violence victims',
       'eastern/indian people', "folks with Alzheimer's", 'Arabians',
       'gay men, bisexual men', 'Indian Women', 'French',
       'lesbian women, gay men, bisexual women, bisexual men',
       'Victims of HIV', 'slaves', 'Alabama',
       'Babies born with addiction', 'pakistan folks',
       'black folks, native american/first nation folks',
       'black folks, indian', 'anorexic',
       'sexual abuse, incest, rape victims',
       'assault victims, incest victims', 'Gendered people',
       'assault victims, child rape victims', 'trafficking victims',
       'assault victims, date rape victims',
       'muslim folks, arabic folks, middle eastern', 'Polish people',
       'gay folks', 'gay men, lgbt', 'indian folk', 'Afghanistan',
       'Afghan people', 'Afghani people', 'Blind folks',
       'child sex abuse', 'Farmers', 'Palestine', 'Ethiopian People',
       'home school kids', 'gay men, trans women',
       'assault victims, Necrophilia victims', 'American folks',
       'african people', 'sex crime victims', 'feminist',
       'people of color', "Anyone that isn't White.", 'Saudis', 'Israel',
       'Israel folks',
       'black folks, asian folks, latino/latina folks, native american/first nation folks, all non-whites',
       'Libyan folks', 'Catholics', 'holocaust victimes',
       'black folks, white people', 'queer people',
       'domestic violence victims', 'Gypsies/ Romani', 'disaster',
       'Aboriginals', 'isis members', 'sexual abuse, incest victims',
       'school kids', 'White folks', 'black folks, asian folks, Indians',
       'starvation victims', 'black folks, Africans', 'Chinese',
       'muslim folks, Pakistan', 'Country music lovers',
       'black folks, police', 'Sexual assault, rape victims',
       'catholic folks', 'disasters', 'Scottish', 'irish', 'poor whites',
       'assault victims, Sexual assault, rape victims',
       'shooting victims (not mass shooting)', 'all lgtb folks',
       'irish folk', 'gay men, trans men, bisexual men',
       'jewish folks, african folks', 'police officers', 'emos',
       'Nonbinary people', 'little people',
       'women, gay men, bisexual men', 'Syrian folks', 'all minorities',
       'jewish folks, christian folks', 'deaf people',
       'jewish folks, New Yorkers', 'jewish folks, Hebrew', 'Nigeria',
       'People from India', 'india', 'Germans', 'german folks',
       'catholic', 'famine victims', 'people from the middle east',
       'policemen', 'people involved in police brutality',
       'sexually abused kids.', 'war victims', 'Kurds',
       'human trafficking victims', 'sex slaves', 'Alabama, USA',
       'mass shooting victims, murder victims', 'Asian', 'coma patients',
       'Arabs', 'Sex trafficking victims', 'gypsies', 'Gypsies', 'roma',
       'kidnapping victims', "people who's fathers have left them",
       'black folks, asian folks, latino/latina folks',
       'black folks, latino/latina folks, indian folks',
       'untimely death victims', 'Violent crime victims',
       'victims of sexual assualt', 'victims of forced migration',
       'aborted children', 'dead people',
       'physically disabled folks, folks with physical illness/disorder, mentally disabled folks',
       'scottish', 'Mexican people', 'miscarriage',
       'Waterboarding victims', 'Suicidal people',
       'child molestation victims; incest victims', 'Irishmen',
       'KKK victims', 'parents who have experienced SIDS', 'Autistic',
       'autistic children', 'puerto ricans', 'Anti-vaxxers',
       'drugged victims', 'taliban', 'chinese', 'domestic abuse victims',
       'Blind people', 'tragedy victims', 'rape victim', 'german',
       'Potential suicide victims', 'Alabamians', 'rural Americans',
       'Miscarriage survivors', 'ethiopian', 'Sexual assault victims',
       'white guys', 'women who have had miscarriages', 'Somali',
       'somolia', 'sjws', 'Atom bombing of Japan in WWII',
       'Chinese Folks', 'molestation victims', "Parkinson's",
       'Kazakhstan', 'terrorism victims, holocaust victims',
       'black folks, white men', 'Sudanese', 'Sudanese folks',
       'child sexual abuse victims', 'abuse victims', 'homeless folks',
       'victims of 9/11', 'asians', 'porn actors',
       'black victims of police shootings', 'jamaicans',
       'asian folks, Jamaican', 'Syrian civilians affected by war',
       'black folks, Jewish folks', '"incels"',
       'mass shooting victims, child rape victims',
       'jewish folks, all groups targeted by nazis', 'cancer surivors',
       'denmark, islamic', 'Europeans', 'Middle East',
       'harassment victims, child rape victims', 'Iraqi victims of war',
       'blind women', 'Furry', 'homeless people', 'japanese women',
       'WWII Nuclear bombing victims', 'brazilian folks', 'POC',
       'Homeless', 'women, trans women, trans men', 'Slaves',
       'the handicapped', 'Mormons', 'victims of child sexual abuse',
       'Animal crime victims', 'Child murder', 'kenyans', 'Kenyans',
       'women, Non-Binary Gender Fluid Demi-queer Pan sexual', 'Ireland',
       'thai people', 'Thai people', 'anti vaxxers', 'folks with cancer',
       'iranian folks', 'Police shooting victim', 'North Korea',
       'Afghani', 'rape and murder victims', 'abortions',
       'people with leprosy', 'victims of cannibalism', 'Hippies',
       'abuse survivors', 'little girls', 'black folks, Russian folks',
       'jewish folks, russians', '"rednecks"', 'muslim women',
       'Bangladeshi', 'bangladesh teens', 'somalian children',
       'Somali folks', 'children who died young of diseases',
       'middle aged men',
       'black folks, latino/latina folks, native american/first nation folks, anyone not white',
       'Italian', 'italian', 'harassment victims, Bullying victims',
       'Middle Eastern folks', 'Sick people', 'Anorexic', 'German folks',
       'Suicide attempt victims', 'black victims of racial abuse', 'jews',
       'canadians', 'old folks, overweight/fat folks',
       'Alzheimer patients', 'people who have had miscarriages',
       'WWII victims', 'assault victims, rape, pedophilia victims',
       'native american/first nation folks, Indians', 'Nigerian folks',
       'China', 'people with anorexia', 'vegan', 'Autism',
       'miscarriage victims', 'Teens', 'Asia', 'Islamics', 'Islamists',
       'feminine men', 'islamic', 'Saudi Arabians', 'teenage girls',
       'girls', 'shia', 'liberals, Feminists', 'cis', 'Reddit',
       'minorities', 'sierra leone',
       "cops (don't know if this is an identity group)", 'skinny men',
       'pedophiles', 'Emo people', 'christian folks, islamic folks',
       'muslim folks, christian folks', 'dog owners',
       'assault victims, police officers', 'French people',
       'people from rwanda', 'ethiopian folks',
       'climate disaster victims, mass shooting victims, terrorism victims, assault victims, harassment victims',
       'rednecks/South region in the US', "'rednecks'", 'hookers',
       "Jehovah's Witnesses", 'LGBT youth', 'romanians', 'lawyers',
       'white folk', 'christian folks, Catholics', 'Syrian people',
       'not specified',
       'trans women, trans men, bisexual women, bisexual men',
       'french canadian folks', 'french folks', 'war vets', 'jewish',
       'disease victims', 'millennials', 'mu slims',
       'middle eastern / arabic people',
       'trans women, trans men, Non-binary people', 'saudi arabians',
       'ALL', 'sexual assualt', 'women, bisexual men', 'emo kids',
       'southern white people', 'harassment victims, rape victims',
       'dead babies', 'black folks, whites', 'BLM',
       'Everyone/parents/children', 'homosexuals',
       'police shooting vicitms', 'black folks, irish', 'judges',
       'Pakistani folks', 'black folks, african', 'alabamians',
       'trans people', 'Scottish people', 'cis men', 'Armenians',
       'armenian', 'muslim', 'black folks, interracial couples',
       'black folks, asian folks, latino/latina folks, native american/first nation folks, all races',
       'latino/latina folks, Irish, Scottish', 'pollack', 'Southerns',
       'Boston Marathon victims', 'black folks, muslims',
       'Sexual assault victim.', 'hunger victims', 'Palestinian woman',
       'Spousal abuse victims', 'men with small penises', 'toddlers',
       'somalians', 'Police', 'black folks, irish folks',

In [30]:
def normalize_target_SBIC(x):
    if pd.isna(x):
        return ["none"]

    x = str(x).strip().lower()
    x = re.sub(r"\s+", " ", x)

    if x in ["", "nan", "none", "unknown", "not specified", "everyone", "all", "all minorities"]:
        return ["none"]

    # Plusieurs targets séparées par virgules
    parts = [p.strip() for p in re.split(r",|/|;", x)]
    mapped = [normalize_single_target(p) for p in parts if p.strip()]

    # Enlever none si d'autres targets existent
    mapped = [m for m in mapped if m != "none"]

    if len(mapped) == 0:
        return ["none"]

    # Si plusieurs catégories, garder la première après mapping
    # ou remplacer par random/majority selon ton pipeline
    return mapped


def normalize_single_target(x):
    x = str(x).strip().lower()
    x = re.sub(r"\s+", " ", x)

    if x in ["", "nan", "none", "unknown", "not specified"]:
        return "none"

    # Race / ethnicity
    if any(k in x for k in [
        "black", "white", "asian", "latino", "latina", "hispanic",
        "native american", "first nation", "indigenous", "aboriginal",
        "poc", "people of color", "colored", "non-white", "non white",
        "nonwhite", "minority", "minorities", "mixed race", "biracial",
        "caucasian", "mexican", "arab", "middle eastern", "indian",
        "pakistani", "chinese", "japanese", "korean", "thai", "vietnamese",
        "african", "ethiopian", "somali", "nigerian", "jamaican",
        "gypsy", "romani", "roma", "slavic", "skin"
    ]):
        return "race"

    # Religion
    if any(k in x for k in [
        "muslim", "islam", "islamic", "jew", "jewish", "hebrew",
        "christian", "catholic", "mormon", "jehovah", "buddhist",
        "hindu", "atheist", "religion", "religious", "holocaust",
        "anti-semitism", "antisemitism"
    ]):
        return "religion"

    # Gender
    if any(k in x for k in [
        "women", "woman", "men", "man", "male", "female", "girls",
        "boys", "mothers", "fathers", "pregnant", "feminist",
        "feminists", "gender neutral", "non-binary", "nonbinary",
        "third gender", "genderqueer", "cis", "breast", "penis"
    ]):
        return "gender"

    # Sexual orientation / LGBTQ+
    if any(k in x for k in [
        "gay", "lesbian", "bisexual", "trans", "lgbt", "lgbtq",
        "queer", "homosexual", "homosexuals", "asexual",
        "sexual orientation", "sexuality", "heterosexual",
        "incel", "incels", "virgin", "sex workers", "prostitutes",
        "porn stars", "hookers"
    ]):
        return "sexual_orientation"

    # Immigration / refugees
    if any(k in x for k in [
        "immigrant", "immigrants", "illegal immigrants", "refugee",
        "refugees", "dreamers", "foreigners", "asylum"
    ]):
        return "immigration_status"

    # Nationality / regional origin
    if any(k in x for k in [
        "american", "americans", "canada", "canadian", "england",
        "british", "irish", "scottish", "welsh", "french", "german",
        "italian", "polish", "greek", "turkish", "syrian", "syria",
        "russian", "russia", "ukrainian", "ukrainians", "iranian",
        "afghan", "afghanistan", "palestinian", "palestine", "israel",
        "israeli", "saudi", "iraqi", "kurds", "romania", "romanians",
        "albanian", "albanians", "brazilian", "brazilians",
        "venezuelan", "venezuelans", "malaysian", "cambodian",
        "puerto rican", "sudanese", "kenyan", "kenyans", "texans",
        "southerners", "southern", "alabama", "rural americans",
        "nationality", "country", "european", "europeans", "asia",
        "africa", "middle east", "north korea", "south korea",
        "india", "pakistan", "china", "japan", "mexico"
    ]):
        return "nationality"

    # Disability / physical or mental disability
    if any(k in x for k in [
        "disabled", "disability", "physically disabled", "mentally disabled",
        "mental illness", "mental disorder", "ocd", "autistic", "autism",
        "down syndrome", "dwarfism", "midget", "little people",
        "blind", "deaf", "speech impediment", "paralysis", "handicapped",
        "alzheimer", "parkinson", "leprosy"
    ]):
        return "disability"

    # Class / social status
    if any(k in x for k in [
        "poor", "poverty", "homeless", "rich", "well off", "working class",
        "class", "welfare", "starvation", "hunger"
    ]):
        return "class"

    # Politics / ideology
    if any(k in x for k in [
        "conservative", "conservatives", "republican", "republicans",
        "liberal", "liberals", "democrat", "democrats", "leftist",
        "right-wing", "alt right", "alt-right", "antifa", "anti-fa",
        "fascist", "fascists", "communist", "communists", "socialist",
        "socialists", "trump", "blm", "blacklivesmatter", "sjw",
        "social justice warrior", "politician", "politicians",
        "political", "politics", "ideology", "gun control advocates",
        "gun enthusiasts", "pro-life advocates", "climate deniers"
    ]):
        return "politics"

    # Violence / victims / crime / war
    if any(k in x for k in [
        "victim", "victims", "assault", "rape", "murder", "homicide",
        "molestation", "abuse", "domestic violence", "violence",
        "kidnap", "trafficking", "terrorism", "war", "genocide",
        "slavery", "slaves", "shooting", "bombing", "attack",
        "crime", "violent", "death", "dead", "suicide victims",
        "holocaust victims", "pearl harbor", "911", "chernobyl",
        "nuclear bombing", "disaster victims", "fire victims",
        "accident victims", "car crash", "plane crash", "waterboarding"
    ]):
        return "violence"

    # Health
    if any(k in x for k in [
        "health", "cancer", "patients", "hiv", "aids", "disease",
        "illness", "sick", "terminally ill", "anorexic", "anorexia",
        "bulimia", "suicidal", "self-harm", "addiction", "drug",
        "coma", "miscarriage", "sids", "ebola", "leprosy"
    ]):
        return "health"

    return "other"

In [31]:
df_SBIC = pd.DataFrame()
df_SBIC["text"] = df_SBIC_raw["post"]
df_SBIC["hate_label"] = (df_SBIC_raw["offensiveYN"] >= 0.5).astype(int)
df_SBIC["style"] = df_SBIC_raw['targetStereotype'].isna().apply(lambda x: 1 if x else 0)  # implicit if stereotype is present, explicit if not
df_SBIC["target_list"] = df_SBIC_raw['targetMinority'].apply(normalize_target_SBIC)
df_SBIC["target_conf"] = 1.0

# Clean text column
df_SBIC = df_SBIC.dropna(subset=["text"])
df_SBIC["text"] = df_SBIC["text"].astype(str)

In [32]:
from collections import Counter
import random

rng = random.Random(42)

def majority_label(series):
    values = series.dropna().tolist()
    if len(values) == 0:
        return np.nan
    return Counter(values).most_common(1)[0][0]

def majority_target(series):
    all_targets = []

    for targets in series:
        all_targets.extend(targets)

    if len(all_targets) == 0:
        return "none"

    counts = Counter(all_targets)
    max_count = max(counts.values())

    top_targets = [k for k, v in counts.items() if v == max_count]

    # if multiple top targets, return random choice among them (tie-break)
    return rng.choice(top_targets)

df_SBIC_agg = (
    df_SBIC
    .groupby("text", as_index=False)
    .agg(
        avg=("hate_label", "mean"),
        hate_label=("hate_label", lambda x: int(x.mean() >= 0.5)),
        style=("style", majority_label),
        target=("target_list", majority_target),
        target_conf=("target_conf", "mean"),
    )
)

df_SBIC_agg["style"] = df_SBIC_agg["style"].astype(int)
df_SBIC_agg["target_conf"] = 1.0

In [33]:
df_SBIC_final = df_SBIC_agg[
    ["text", "hate_label", "style", "target", "target_conf"]
].copy()

In [34]:
df_SBIC_implicit = df_SBIC_final[df_SBIC_final["style"] == 0].copy()
df_SBIC_explicit = df_SBIC_final[df_SBIC_final["style"] == 1].copy()

In [35]:
df_SBIC_final.drop(columns=["target", "target_conf"], inplace=True)
#df_SBIC_final.to_csv("sbic_combined.csv", index=False)

## HateCOT Dataset

We gave the following prompt to GPT 5.5:

"You are an expert annotator able to distinguish explicit and implicit text. I have the following HateCOT dataset. I want you to go through every text and explanation to determine if the text is explicit (direct, clear, and literal, leaving no doubt about the speaker's intent) or implicit (indirect, implied, or suggested, requiring to infer meaning from context or tone). Add 2 columns to the dataset: one style column containing 0 if the text is implicit, and 1 if it is explicit. The second column is style explanation where you briefly explain why it is implicit / explicit"

And itered this prompt 5 times, obtaining 5 datasets. We averaged the results to obtain a more stable style across texts and explanations.

In [70]:
df_hatecot_raw = pd.read_csv("hatecot_final_D3.csv")

In [71]:
df_hatecot_style_1 = pd.read_csv("hatecot_final_D3_style_1.csv")
df_hatecot_style_2 = pd.read_csv("hatecot_final_D3_style_2.csv")
df_hatecot_style_3 = pd.read_csv("hatecot_final_D3_style_3.csv")
df_hatecot_style_4 = pd.read_csv("hatecot_final_D3_style_4.csv")
df_hatecot_style_5 = pd.read_csv("hatecot_final_D3_style_5.csv")

In [72]:
df_hatecot_style = pd.concat([df_hatecot_style_1, df_hatecot_style_2, df_hatecot_style_3, df_hatecot_style_4, df_hatecot_style_5], ignore_index=True)
df_hatecot_style = df_hatecot_style.drop(columns=["style explanation"])

In [73]:
df_hatecot_style = df_hatecot_style[df_hatecot_style['domain'] != 'dynahate'].copy() # dynhate already in initial dataset

In [74]:
hate_labels = {
    "Hate",
    "Hate Speech",
    "Hateful",
    "Identity Directed Abuse",
    "Affiliation Directed Abuse",
    "Person Directed Abuse",
    "Toxic",
}

non_hate_labels = {
    "Neutral",
    "Benign",
    "Normal",
    "Not Hate Speech",
    "Not Offensive",
    "Not Hate",
    "Offensive",
}

In [75]:
def map_hateful_label(label):
    if label in hate_labels:
        return 1
    if label in non_hate_labels:
        return 0
    return None  # unclear / not necessarily hate

df_hatecot_style["hate_label"] = df_hatecot_style["label"].apply(map_hateful_label)
df_hatecot_style = df_hatecot_style[df_hatecot_style["hate_label"].notna()].copy()

df_hatecot_style['text'] = df_hatecot_style['post'].astype(str)
df_hatecot_style['target_conf'] = 1.0

In [76]:
df_hatecot_style.target.unique()
#pd.DataFrame(df_hatecot_style.target.unique()).to_csv(
 #   "hatecot_targets.csv",
  #  index=False
#)

array(['middle eastern', nan, 'muslim', 'Men', 'jewish',
       'Asian , Black or African American , Latino or non-white Hispanic , Middle Eastern , Native American or Alaska Native , Pacific Islander , Non-Hispanic White , Christian , Jewish , Mormon , Muslim , Men , Women',
       'people with physical disability',
       'Asian , Black or African American , Latino or non-white Hispanic , Middle Eastern , Native American or Alaska Native , Pacific Islander , Non-Hispanic White , Atheist , Buddhist , Christian , Hindu , Jewish , Mormon , Muslim , Immigrant , Non-binary people , Transgender men , Transgender (unspecififed) , Transgender women',
       'red haired people  |  Red-haired persons', 'Non-Hispanic White',
       'Christian , Atheist , Buddhist , Hindu , Jewish , Mormon , Muslim',
       'Women', 'lgbtq', 'Christian , Jewish , Muslim', 'women',
       'chinese',
       'People of other origin , People from some specific country',
       'native american', 'Muslim , People of other origin',
       'Muslim , People from some specific country',
       'Immigrant , Undocumented person', 'people with mental disorder',
       'asian', 'Christian', 'black',
       'Non-Hispanic White , Black or African American , Men',
       'Men , Women', 'mexican', 'Women , Men', 'latino',
       'Black or African American , Men', 'Black or African American',
       'Native American or Alaska Native , Immigrant , People from some specific country',
       'People from some specific country',
       'Non-binary people , Transgender men , Transgender (unspecififed) , Transgender women',
       'People from some specific country , Undocumented person , Immigrant , Migrant worker , Children , Adolescent',
       'Non-Hispanic White , Men , Young adults',
       'Black or African American , Women',
       'Non-Hispanic White , Other races',
       'Latino or non-white Hispanic , Non-Hispanic White , Immigrant , Migrant worker , People from some specific country , Undocumented person , People of other origin',
       'Middle Eastern , Non-Hispanic White , Black or African American',
       'Jewish', 'People with mental health problems',
       'Black or African American , Latino or non-white Hispanic',
       'Other gender , Children , People with mental health problems , People with cognitive disorders or learning disabilities',
       'Muslim', 'Women , Non-binary people , Transgender men',
       'Jewish , Muslim , People from some specific country',
       'Asian , Women',
       'Native American or Alaska Native , Non-Hispanic White',
       'Men , Transgender women', 'Transgender men , Women',
       'Middle Eastern , Hindu , Men , Women',
       'Middle Eastern , Other races , People from some specific country',
       'black folks',
       'Asian , Black or African American , Latino or non-white Hispanic , Middle Eastern , Native American or Alaska Native , Pacific Islander , Non-Hispanic White , Atheist , Buddhist , Christian , Hindu , Jewish , Mormon , Muslim , Men , Non-binary people , Transgender men , Transgender (unspecififed) , Transgender women , Women',
       'Black or African American , Women , Men',
       'Asian , Transgender women , Transgender men , Transgender (unspecififed)',
       'Other relegions , Christian',
       'Black or African American , Transgender (unspecififed) , Women , Transgender men',
       'People with other disabilities',
       'Black or African American , Other races , People from some specific country',
       'Middle Eastern , Muslim , Immigrant , People from some specific country',
       'Non-binary people , Transgender (unspecififed) , Transgender women , Women',
       'Black or African American , People from some specific country , People with cognitive disorders or learning disabilities',
       'Other races , Non-Hispanic White , Men , Women',
       'Latino or non-white Hispanic , Women', 'whites  |  liberals',
       'Black or African American , Other races',
       'Asian , People from some specific country',
       'Asian , Immigrant , People from some specific country',
       'Middle Eastern , Muslim',
       'Men , Women , Non-binary people , Transgender men , Transgender (unspecififed) , Transgender women',
       'Asian , People from some specific country , Women',
       'women, lesbian women, trans women, bisexual women',
       'Immigrant , Migrant worker , Undocumented person',
       'Asian , Black or African American , Latino or non-white Hispanic , Middle Eastern , Native American or Alaska Native , Pacific Islander , Non-Hispanic White , Other races',
       'Children', 'Women , Young adults',
       'Men , People with mental health problems',
       'Middle Eastern , Muslim , People from some specific country',
       'Other races , Non-Hispanic White', 'Non-Hispanic White , Men',
       'Non-Hispanic White , Christian , People from some specific country',
       'Transgender women , Women , Transgender men',
       'Women , People with unspecified disability',
       'Non-Hispanic White , Native American or Alaska Native , Immigrant , People from some specific country',
       'Asian , Black or African American , Latino or non-white Hispanic , Middle Eastern , Native American or Alaska Native , Pacific Islander , Other races',
       'Non-Hispanic White , Christian , People from some specific country , Women',
       'Pacific Islander , People from some specific country', 'gay men',
       'Latino or non-white Hispanic , Immigrant , Migrant worker , People from some specific country , Undocumented person , People of other origin',
       'Middle Eastern , Muslim , Women',
       'Latino or non-white Hispanic , People from some specific country , Undocumented person',
       'Non-Hispanic White , Other races , People from some specific country',
       'Latino or non-white Hispanic , Middle Eastern , Immigrant , Migrant worker , People from some specific country , Undocumented person',
       'Atheist', 'Immigrant , People of other origin', 'muslim folks',
       'Undocumented person , Immigrant',
       'Black or African American , Non-Hispanic White',
       'People from some specific country , Immigrant',
       'Immigrant , People from some specific country , Undocumented person',
       'Undocumented person , Immigrant , Migrant worker',
       'Non-Hispanic White , Men , Seniors', 'Asian , Pacific Islander',
       'Men , Women , Adolescent , Young adults , Middle aged people',
       'Asian',
       'Asian , Black or African American , Latino or non-white Hispanic , Middle Eastern , Non-Hispanic White , Immigrant , Migrant worker , People from some specific country , Undocumented person',
       'Non-Hispanic White , Muslim , Immigrant , Migrant worker , Undocumented person',
       'Black or African American , People from some specific country',
       'Christian , Jewish , Mormon , Muslim',
       'Men , Transgender (unspecififed)', 'Other races',
       'Non-Hispanic White , Other races , Jewish , People from some specific country , Immigrant',
       'right-wing people (alt-right)', 'lesbian women', 'Middle Eastern',
       'women  |  old folks, ugly folks',
       'people with mental disabilities',
       'minorities  |  black folks, latino/latina folks',
       'feminists (trans-exclusionary radical)', 'liberals',
       'Transgender men',
       'People with unspecified disability , People with cognitive disorders or learning disabilities',
       'catholics', 'women  |  assault victims', 'involuntary celibates',
       'communists', 'ethiopians  |  Ethiopians  |  Ethiopia',
       'jewish folks',
       'Latino or non-white Hispanic , Immigrant , Migrant worker , Undocumented person',
       'activists (anti-fascist)', 'socialists', 'moderators',
       'incest victims', 'left-wing people', 'republicans', 'gamers',
       'People from some specific country , Women', 'white people',
       'Jewish , Women', 'shorts folks',
       'lesbian women  |  folks with physical illness/disorder  |  women',
       'Ethiopians', 'Middle Eastern , People from some specific country',
       'lesbian women  |  anyone who is gay  |  lesbian women, gay men',
       'Other races , Jewish', 'jewish folks  |  holocaust victims',
       'Transgender (unspecififed) , Women',
       'Women , People with mental health problems',
       'non-gender dysphoric transgender people',
       'mentally disabled folks',
       'Women , Men , Non-binary people , Transgender men , Transgender (unspecififed) , Transgender women',
       'murder victims', 'christian folks  |  Catholics',
       'People with cognitive disorders or learning disabilities',
       'disabled folks',
       'Women , People with cognitive disorders or learning disabilities , People with other disabilities',
       'Latino or non-white Hispanic , Other races',
       'people from pakistan', 'feminists',
       'physically disabled folks  |  folks with physical illness/disorder',
       'people with physical disabilities', 'Men , Young adults',
       'women  |  black folks', 'Indians  |  indian folks',
       'jewish folks  |  black folks',
       'ethnic minorities , sexual and gender minorities',
       'Holocaust victims  |  jewish folks', 'terrorism victims',
       'jewish folks  |  terrorism victims',
       'Non-Hispanic White , People from some specific country',
       'assault victims', 'men  |  women', 'sexual and gender minorities',
       'transgender people', 'left-wing people , moderators',
       'shorts folks  |  women  |  People of Color',
       'gay men , people from america',
       'Christian , People with unspecified disability',
       'christian folks  |  gay men', 'donald trump supporters',
       'asian folks', 'muslims',
       'mentally disabled folks  |  folks with mental illness/disorder',
       'Native American or Alaska Native',
       'Non-Hispanic White , Christian',
       'Non-Hispanic White , Black or African American , Men , Women',
       'mentally disabled folks  |  women',
       'folks with physical illness/disorder, folks with mental illness/disorder, mentally disabled folks  |  folks with mental illness/disorder',
       'black folks, asian folks, latino/latina folks',
       'women, feminists  |  assault victims  |  feminists',
       'black people', 'children  |  women  |  kids',
       'Middle Eastern , Non-Hispanic White , Muslim , Undocumented person',
       'black folks, asian folks, latino/latina folks, native american/first nation folks',
       'babies  |  assault victims',
       'jewish folks  |  gay men  |  Holocaust victims', 'prostitutes',
       'car accident victims', 'people with dwarfism',
       'black folks  |  Jamacian  |  Jamaica', 'lgbtqa community',
       'Asian , Black or African American , Latino or non-white Hispanic , Middle Eastern , Native American or Alaska Native , Pacific Islander , Other races , Non-Hispanic White , People of other origin',
       'trans women, trans men',
       'Atheist , Buddhist , Christian , Hindu , Jewish , Mormon , Muslim',
       'overweight/fat folks', 'People of other origin',
       'Non-Hispanic White , Women , Men',
       'women  |  mass shooting victims',
       'left-wing people (social justice)', 'Christian , Other relegions',
       'atheists', 'teachers', 'syrians  |  arabic folks',
       'Men , People with cognitive disorders or learning disabilities',
       'People of other origin , Men', 'people with autism',
       'activists (animal rights)',
       'Non-Hispanic White , Black or African American , Christian',
       'folks with physical illness/disorder, mentally disabled folks  |  mentally disabled folks  |  physically disabled folks, folks with physical illness/disorder, folks with mental illness/disorder, mentally disabled folks',
       'Non-Hispanic White , Women , Children , Adolescent , Young adults',
       'people from mexico', 'black folks  |  assault victims',
       'Feminists  |  feminists',
       'Middle Eastern , Latino or non-white Hispanic , Black or African American , People from some specific country',
       'sexual assault victims',
       'Asian , Black or African American , Latino or non-white Hispanic , Middle Eastern , Native American or Alaska Native , Pacific Islander , Other races , Immigrant , Undocumented person',
       'Other races , Middle Eastern , Non-Hispanic White , Jewish , Immigrant , People from some specific country',
       'people with mental disabilities , people from america',
       'women, lesbian women, trans women, bisexual women  |  women',
       'Men , Transgender men , Transgender (unspecififed) , Transgender women',
       'native american/first nation folks',
       'Indians  |  native american/first nation folks', 'catholic folks',
       'people of color  |  black folks  |  black folks, asian folks, latino/latina folks, native american/first nation folks, indian folks, any folks with brown skin',
       'jewish folks, christian folks', 'orphans',
       'Non-Hispanic White , People of other origin , People with mental health problems',
       'people from india', 'black folks  |  women',
       'overweight/fat folks  |  feminists  |  women',
       'ethiopians  |  black folks  |  Ethiopia',
       'gay men  |  black folks',
       'Asian , Black or African American , Latino or non-white Hispanic , Middle Eastern , Native American or Alaska Native , Pacific Islander , Non-Hispanic White , Men , Transgender men , Transgender women , Women , Transgender (unspecififed) , Non-binary people , Other gender',
       'Men , Other gender , Transgender women', 'police officers',
       'Women , Transgender women', 'jewish people',
       'sexual and gender minorities , black people , rich people , transgender people',
       'Latino or non-white Hispanic , People from some specific country',
       'gay people', 'Immigrant', 'democrats',
       'Africa  |  black folks  |  Ethiopia',
       'jewish folks  |  Holocaust victims',
       'police officers  |  mixed folks  |  cops  |  black folks, asian folks, latino/latina folks, native american/first nation folks',
       'Asian , Latino or non-white Hispanic , Middle Eastern , Pacific Islander , Other races , Immigrant , Migrant worker , Undocumented person , Non-binary people , Transgender men , Transgender (unspecififed) , Transgender women , Women',
       'latino/latina folks', 'Men , Women , Other gender',
       'People with cognitive disorders or learning disabilities , People with unspecified disability',
       'Black or African American , Men , Women', 'women , gamers',
       'Asian , Middle Eastern , People from some specific country',
       'non-white people',
       'Non-Hispanic White , Black or African American , Latino or non-white Hispanic',
       'Incel men', 'muslim folks  |  syrians',
       'Sexual assault, rape victims', 'Other relegions',
       'black folks  |  black folks, asian folks, latino/latina folks, native american/first nation folks',
       'office workers - charities',
       'Black or African American , Middle Eastern , People from some specific country',
       'people from america',
       'Asian , Black or African American , Latino or non-white Hispanic , Middle Eastern , Pacific Islander , Migrant worker , People of other origin , People with other disabilities',
       'Latino or non-white Hispanic',
       'jewish folks, Catholic priests  |  priests',
       'Men , Transgender men , Transgender (unspecififed) , Transgender women , Women',
       'Seniors', 'Jewish , Children', 'black folks  |  kids',
       'people from africa', 'elderly people',
       'Black or African American , Men , Transgender men , Transgender women , Women , Other gender',
       'jewish folks  |  Jewish folks', 'right-wing people',
       'black folks  |  liberals', 'arabs , people from mexico',
       'arabic folks, immigrants  |  arabic folks',
       'assault victims  |  pedophilia victims',
       'Transgender (unspecififed)',
       'women  |  Domestic abuse victims  |  assault victims',
       'Other races , Immigrant , Other gender , Women',
       'black folks  |  women  |  black folks, asian folks, latino/latina folks, native american/first nation folks',
       'Other races , Immigrant , People from some specific country',
       'hindus', 'muslim folks  |  terrorism victims', 'heterosexuals',
       'christian folks  |  folks with physical illness/disorder',
       'Black or African American , Transgender women , Women',
       'Transgender men , Transgender (unspecififed) , Transgender women',
       'Young adults , People with physical disability , People with mental health problems',
       'black people , gay men',
       'Black or African American , Latino or non-white Hispanic , Other races , Middle Eastern , Immigrant , Undocumented person',
       'women , donald trump supporters', 'Non-Hispanic White , Women',
       'Hispanic folks  |  latino/latina folks',
       'Women , Men , Transgender women , People with cognitive disorders or learning disabilities',
       'Transgender men , Men , Women',
       'africans  |  African  |  Africans', 'minority folks',
       'Asian , Black or African American , Middle Eastern , People from some specific country',
       'Non-Hispanic White , People from some specific country , Immigrant',
       'Non-Hispanic White , People with mental health problems',
       'Men , Non-binary people , Transgender men , Transgender (unspecififed) , Transgender women , Women',
       'libertarians', 'physically disabled folks  |  black folks',
       'Jewish , Immigrant , People from some specific country',
       'Muslim , Immigrant , People from some specific country , Undocumented person',
       'transgender women',
       'Black or African American , Transgender (unspecififed)',
       'Muslim , Immigrant',
       'Black or African American , Latino or non-white Hispanic , Non-Hispanic White',
       'Non-Hispanic White , Jewish',
       'folks with physical illness/disorder',
       'Immigrant , People from some specific country',
       'Middle Eastern , Muslim , People of other origin',
       'War victims  |  WWII Atomic Bomb victims',
       'Black or African American , Non-Hispanic White , Other races',
       'Jewish , People from some specific country', 'Transgender women',
       'Other races , People from some specific country',
       'Atheist , Buddhist , Christian , Hindu , Jewish , Mormon , Muslim , Other relegions , Women',
       'mass shooting victims',
       'Latino or non-white Hispanic , Non-Hispanic White , Immigrant , Migrant worker',
       'Black or African American , People with cognitive disorders or learning disabilities',
       'Non-binary people , Transgender (unspecififed)',
       'left-wing people (far left) , communists', 'gay men , black men',
       'men', 'rich people',
       'Transgender (unspecififed) , Transgender women , Non-binary people , Transgender men',
       'sexual and gender minorities , non-gender dysphoric transgender people',
       'Latino or non-white Hispanic , Black or African American , Middle Eastern',
       'black folks  |  asian folks',
       'latino/latina folks  |  overweight/fat folks',
       'Black or African American , Non-Hispanic White , Women , Men',
       'middle eastern / arabic people  |  arabs  |  muslim folks',
       'Black or African American , Middle Eastern , Muslim , Immigrant , People from some specific country',
       'black folks  |  mexican folks  |  black folks, latino/latina folks',
       'Women , Non-binary people , Transgender women', 'conservatives',
       'Africans  |  black folks',
       'Transgender (unspecififed) , Transgender men , Women',
       'black folks  |  African folks', 'assault victims  |  women',
       'Other races , Middle Eastern , People from some specific country',
       'religious people', 'Asian , Immigrant',

In [77]:
hatecot_target_mapped = pd.read_csv("hatecot_targets_mapped.csv")

hatecot_target_mapped["category"] = (
    hatecot_target_mapped["category"]
    .astype(str)
    .str.strip()
    .str.lower()
)

In [78]:
import re
import pandas as pd

CANONICAL_TARGETS = {
    "none", "race", "religion", "gender", "sexual_orientation",
    "immigration_status", "nationality", "disability", "class",
    "politics", "violence", "health", "other"
}

def normalize_single_target(x):
    if pd.isna(x):
        return "none"

    x = str(x).strip().lower()
    x = re.sub(r"\s+", " ", x)

    if x in {"", "nan", "none", "unknown", "not specified"}:
        return "none"

    if any(k in x for k in [
        "asian", "black", "african american", "latino", "hispanic",
        "middle eastern", "native american", "alaska native",
        "pacific islander", "non-hispanic white", "white", "people of color",
        "poc", "non-white", "non white", "minorities", "minority",
        "mexican", "chinese", "indian", "arab", "arabic", "ethiopian",
        "racial", "ethnic", "race", "other races"
    ]):
        return "race"

    if any(k in x for k in [
        "muslim", "islam", "islamic", "christian", "catholic",
        "jewish", "jew", "mormon", "hindu", "buddhist", "atheist",
        "religion", "religious", "other relegions", "other religions",
        "holocaust"
    ]):
        return "religion"
    
    if any(k in x for k in [
        "lgbt", "lgbtq", "lgbtqa", "gay", "lesbian", "bisexual",
        "transgender", "trans women", "trans men", "sexual orientation",
        "sexual and gender minorities", "heterosexual", "incel",
        "prostitutes", "sex workers"
    ]):
        return "sexual_orientation"

    if any(k in x for k in [
        "men", "man", "women", "woman", "female", "male",
        "non-binary", "nonbinary", "other gender", "gender",
        "cis", "feminist", "feminists", "girls", "boys"
    ]):
        return "gender"

    if any(k in x for k in [
        "immigrant", "undocumented", "migrant worker", "migrant",
        "refugee", "foreigners"
    ]):
        return "immigration_status"

    if any(k in x for k in [
        "people from some specific country", "country", "nation",
        "american", "ethiopians", "ethiopia", "syrians", "syria",
        "pakistan", "india", "mexico", "japan", "chinese people",
        "russians", "russia", "germans", "irish", "scottish",
        "texas", "floridians", "samoa", "lebanese"
    ]):
        return "nationality"

    if any(k in x for k in [
        "physical disability", "disability", "disabled",
        "unspecified disability", "other disabilities",
        "cognitive disorders", "learning disabilities",
        "hearing impaired", "visually impaired", "autism",
        "aspergers", "dwarfism", "disabled folks"
    ]):
        return "disability"

    if any(k in x for k in [
        "poor", "rich", "working class", "class", "well off",
        "homeless"
    ]):
        return "class"

    if any(k in x for k in [
        "liberal", "conservative", "republican", "democrat",
        "right-wing", "left-wing", "alt-right", "communist",
        "socialist", "antifa", "fascist", "trump", "politic",
        "activists", "moderators", "capitalists", "nationalists",
        "pro choice", "abortion rights"
    ]):
        return "politics"

    if any(k in x for k in [
        "victim", "victims", "assault", "rape", "murder",
        "terrorism", "mass shooting", "war", "holocaust victims",
        "domestic abuse", "domestic violence", "molestation",
        "car accident", "violence", "genocide", "bombing",
        "child rape", "child sexual", "suicide victims",
        "police shooting"
    ]):
        return "violence"

    if any(k in x for k in [
        "mental health", "mental disorder", "mental illness",
        "physical illness", "health", "anorexic", "diabetics",
        "drug problems", "autism", "aspergers", "cancer",
        "seniors", "old folks", "elderly"
    ]):
        return "health"

    return "other"


def normalize_targets(x):
    if pd.isna(x):
        return ["none"]

    x = str(x).strip().lower()

    parts = [
        p.strip()
        for p in re.split(r"\s*\|\s*|\s*,\s*|/|;", x)
        if p.strip()
    ]

    mapped = [normalize_single_target(p) for p in parts]

    mapped = [m for m in mapped if m != "none"]

    mapped = list(dict.fromkeys(mapped))

    return mapped if mapped else ["none"]

In [79]:
target_map = dict(
    zip(
        hatecot_target_mapped["target"],
        hatecot_target_mapped["category"]
    )
)

def normalize_target(x):
    if pd.isna(x):
        return "none"

    return target_map.get(x, "other")

In [80]:
df_hatecot_style["target"] = df_hatecot_style["target"].apply(normalize_target)

In [81]:
from collections import Counter
import random

rng = random.Random(42)

def majority_target(series):
    all_targets = []

    for targets in series.dropna():
        if isinstance(targets, list):
            all_targets.extend(targets)
        else:
            all_targets.append(targets)

    if not all_targets:
        return "none"

    counts = Counter(all_targets)
    max_count = max(counts.values())
    top_targets = [k for k, v in counts.items() if v == max_count]

    return rng.choice(top_targets)

def majority_label(series):
    values = series.dropna().tolist()
    if len(values) == 0:
        return np.nan
    return Counter(values).most_common(1)[0][0]

In [82]:
df_hatecot_agg = (
    df_hatecot_style
    .groupby("text", as_index=False)
    .agg(
        avg=("hate_label", "mean"),
        hate_label=("hate_label", lambda x: int(x.mean() >= 0.5)),
        style=("style", majority_label),
        target=("target", majority_label),
        target_conf=("target_conf", "mean"),
    )
)

In [85]:
df_hatecot_agg.head(10)

,text,avg,hate_label,style,target,target_conf
0,"\r\n""But these laws, which allowed the Church, or a Christian, to appropriate the property of a Jew, can in no sense be considered as",1.0,1,0,religion,1.0
1,"\r\n- [black people are] lazy. they bring crime, they dont contribute positively. they are so lazy they dont even go to school.\r\n",1.0,1,1,nationality,1.0
2,\r\ncrayon:violet>tHIS pAiNTiNG iS bORiNG. iT iS ONLY eL,1.0,1,0,race,1.0
3,""" the core of the religion, alhamdulillah"" -Syed Ahmed ""I look at people on the street, and",0.0,0,1,religion,1.0
4,"""...the myth that suicides are trying to get attention by killing themselves.",1.0,1,0,health,1.0
5,"""I always find that trans activists want to take credit for all the work we do for gay rights, as evidenced in this particular case.""\n",1.0,1,0,sexual_orientation,1.0
6,"""IMPEACH TRUMP"" ""FREE PALESTINE"" ""DIRECT ACTION TO STOP GENOCIDE"" ""I",0.0,0,1,race,1.0
7,"""Islam is the most violent religion""\r\n- ""Malays are the same as the Indonesian/Singaporean""\r\n- ""Australia was discovered",1.0,1,0,race,1.0
8,"""Three [students] followed the school mule on a leash, behind them walked the son of the sexton, doffing his cap",0.0,0,1,health,1.0
9,"""You are ascribing homophobic thoughts that aren't in the posts. The only direct reference to homosexuality was that the sale was anti-gay, which",0.0,0,1,race,1.0

In [87]:
df_hatecot_agg.to_csv("hatecot_combined.csv", index=False)
df_hatecot_explicit = df_hatecot_agg[df_hatecot_agg["style"] == 1].copy()
df_hatecot_implicit = df_hatecot_agg[df_hatecot_agg["style"] == 0].copy()
df_hatecot_explicit.to_csv("hatecot_explicit.csv", index=False)
df_hatecot_implicit.to_csv("hatecot_implicit.csv", index=False)

In [88]:
df_hatecot_implicit.head(10)

,text,avg,hate_label,style,target,target_conf
0,"\r\n""But these laws, which allowed the Church, or a Christian, to appropriate the property of a Jew, can in no sense be considered as",1.0,1,0,religion,1.0
2,\r\ncrayon:violet>tHIS pAiNTiNG iS bORiNG. iT iS ONLY eL,1.0,1,0,race,1.0
4,"""...the myth that suicides are trying to get attention by killing themselves.",1.0,1,0,health,1.0
5,"""I always find that trans activists want to take credit for all the work we do for gay rights, as evidenced in this particular case.""\n",1.0,1,0,sexual_orientation,1.0
7,"""Islam is the most violent religion""\r\n- ""Malays are the same as the Indonesian/Singaporean""\r\n- ""Australia was discovered",1.0,1,0,race,1.0
11,"""dont let your girls grow up to be women, women include lesbians, divorces, single mothers, feminists, and gender equality activists"" a",1.0,1,0,gender,1.0
15,"""otherkin"" the only thing a dogkin hates more than people who keep their dog shedding around their house is people who have allergies",1.0,1,0,race,1.0
16,"""paranoid ideation"" : belief that unwelcome developments are being supervised or coerced by a omnipotent agency. ""Magical thinking"" < the",1.0,1,0,health,1.0
17,"""we can not ignore these countries because they're of strategic importance,"" he said during a speech at the washington institute for near east policy , a",1.0,1,0,race,1.0
26,"( female cats are ""crazy"" ) so this one is on the cat-lady, who probably having a cat and use that as a",1.0,1,0,gender,1.0

## Train, val, test for fine-tuning

In [2]:
from sklearn.model_selection import train_test_split
import pandas as pd

hatecot_combined = pd.read_csv("hatecot_combined.csv")

# 70% train, 30% temp
hatecot_train, hatecot_temp = train_test_split(
    hatecot_combined,
    test_size=0.30,
    random_state=42,
    stratify=hatecot_combined["hate_label"]
)

# 15% val, 15% test
hatecot_val, hatecot_test = train_test_split(
    hatecot_temp,
    test_size=0.50,
    random_state=42,
    stratify=hatecot_temp["hate_label"]
)

hatecot_train.to_csv("hatecot_train.csv", index=False)
hatecot_val.to_csv("hatecot_val.csv", index=False)
hatecot_test.to_csv("hatecot_test.csv", index=False)

print(len(hatecot_train), len(hatecot_val), len(hatecot_test))
print(hatecot_train["hate_label"].mean())
print(hatecot_val["hate_label"].mean())
print(hatecot_test["hate_label"].mean())

10370 2222 2223
0.4085824493731919
0.40864086408640865
0.40845704003598743